### PR TITLE
Feature/analytics code

### LINKED ISSUE #2288: Footer code for platform admin
# Scenario
As owner of an installation of APInf, I want to analyze how users are going through the platform. What do they do, where do they drop off, where do they come from etc.

# Solution
There are a lot of 3rd party tools that are typically integrated with a line of Javascript code added in the bottom of the master template. By adding a field for admins to fill out, we can support any of these.

### PR DESCRIPTION
**Pull request by marla-singer**
Closes #2288

### CODE REVIEW

**Comment by brylie** [comment]
After saving my footer code (`console.log('footer code');`), it seems to work correctly on all pages. However, when navigating from the Organizations page to the Add API page, the footer code does not seem to evaluate:

peek 2017-05-03 15-09

**Comment by brylie** [comment]
After discussing with @marla-singer, we agreed to open a follow-up issue to fix some of the edge cases with this feature. Overall, it is working.

**Comment by philippeluickx** [comment]
@brylie did you open a new issue for this?

Navigation does not seem to be an edge case to me. Is it only when navigating to "Add API" that the footer code is not evaluated?

**Comment by brylie** [comment]
> Navigation does not seem to be an edge case to me. Is it only when navigating to "Add API" that the footer code is not evaluated?

@philippeluickx By 'navigating', I meant 'going from X to Y'. It can be read as 'when going from Organizations page to the Add API page, the footer code does not seem to evaluate'. Hence it was agreed that the work could be continued in a follow-up task.

@marla-singer did you open the follow up task for this issue?

**Comment by marla-singer** [comment]
@philippeluickx @brylie 
#2601

**Pull request merged**
