### PR TITLE
feaure/unique proxy backend base paths

### LINKED ISSUE #1200: Allow only unique proxy backend base paths
In order to avoid having the same API added to the catalog more than once, we should only allow unique API backends. (As a follow-up, we may need to give an option to API owners to report, if someone else have added their API)

# Definition of done
* [ ] User can only add an API with Add API Wizard, if the front-end prefix (proxy backend base path) is unique?
* [ ] If the user tries to add a pre-existing URL (with pre-existing frontend prefix?), they get an error saying that this API backend already exists.

### PR DESCRIPTION
**Pull request by nnn**
Closes #1200

### CODE REVIEW

**Comment by nnn** [comment]
Maybe https://github.com/apinf/platform/pull/1603/commits/fb21892c05f5142607be2f6ed354e57f78e55d07 is unnecessary.

@brylie please test and review.

**Comment by brylie** [comment]
This does not seem to give any validation message when a duplicate 'frontend_prefix' is used.

**Comment by nnn** [comment]
Still can't save API Proxy backend.
@apinf/developers if anyone has time to help me with this. 

A check for uniqueness works but in some cases can't submit the form.

**Comment by brylie** [comment]
I can check. I am getting duplicate key errors, perhaps related to data sync from nightly.umbrella.apinf.io

**Comment by brylie** [comment]
I cleaned up *nightly.umbrella.apinf.io* and configured a local instance of Apinf.

When trying to add a new Proxy Backend, the **Disable API Key** field appears to malfunction:

screenshot from 2016-09-29 10-34-11

Perhaps start a fresh branch from the latest *develop*, and add your changes there.

**Comment by brylie** [comment]
I am able to add a Proxy Backend from Chromium, so we seem to have a Firefox bug related to the **Disable API Key** field.

**Comment by brylie** [comment]
The uniqueness check appears to work in Chromium browser, but there is no user message. I see this in the Chromium console:

```js
errorClass {error: 409, reason: "WriteError({"code":11000,"index":0,"errmsg":"E1100…-aa49-40363121cf57"},"_id":"baahyt4AK9w5f9k3L"}})", details: undefined, message: "WriteError({"code":11000,"index":0,"errmsg":"E1100…40363121cf57"},"_id":"baahyt4AK9w5f9k3L"}}) [409]", errorType: "Meteor.Error"}
details
:
undefined
error
:
409
errorType
:
"Meteor.Error"
message
:
"WriteError({"code":11000,"index":0,"errmsg":"E11000 duplicate key error collection: meteor.proxyBackends index: frontend_prefix_1 dup key: { : null }","op":{"proxyId":"qPDcJkDmLbJbBxYf7","apiId":"DRsTjo7vbEeHAWK3a","apiUmbrella":{"name":"Google 2","frontend_host":"nightly.umbrella.apinf.io","backend_host":"google.com","backend_protocol":"http","servers":[{"host":"google.com","port":80}],"balance_algorithm":"least_conn","url_matches":[{"frontend_prefix":"/google/","backend_prefix":"/"}],"settings":{"disable_api_key":false},"id":"49f65fad-518e-41b9-aa49-40363121cf57"},"_id":"baahyt4AK9w5f9k3L"}}) [409]"
reason
:
"WriteError({"code":11000,"index":0,"errmsg":"E11000 duplicate key error collection: meteor.proxyBackends index: frontend_prefix_1 dup key: { : null }","op":{"proxyId":"qPDcJkDmLbJbBxYf7","apiId":"DRsTjo7vbEeHAWK3a","apiUmbrella":{"name":"Google 2","frontend_host":"nightly.umbrella.apinf.io","backend_host":"google.com","backend_protocol":"http","servers":[{"host":"google.com","port":80}],"balance_algorithm":"least_conn","url_matches":[{"frontend_prefix":"/google/","backend_prefix":"/"}],"settings":{"disable_api_key":false},"id":"49f65fad-518e-41b9-aa49-40363121cf57"},"_id":"baahyt4AK9w5f9k3L"}})"
```

**Comment by nnn** [comment]
Can't add API, even in develop. Gives me the same error message.

**Comment by nnn** [comment]
Closing this. New PR https://github.com/apinf/platform/pull/1722

**Pull request closed without merging**
