### PR TITLE
Feature/edit proxy form fix

### LINKED ISSUE #1532: Edit proxy form not showing existing proxy values
When editing an existing Proxy, under settings > proxies, the form does not include all existing values. Specifically, the following fields are empty, and fail validation:

- API Key
- Auth Token
- Elastic URL

### LINKED ISSUE #1596: Navbar 'proxyPublicDetails' subscription is polluting other views
The 'proxyPublicDetails' publication is used in the *navigation menu* and *API profile view* to control visibility. Both of these templates simply need a count of proxies, rather than any other proxy details.

Add the 'percolatestudio:publish-counts' package and a 'proxyCount' publication, then use the publication on relevant views.

### PR DESCRIPTION
**Pull request by brylie**
Closes #1532 
Closes #1596 

# Changes
- clean code
  - unneeded helpers
  - added comments
  - unneeded data context
- add tmeasday:publish-counts
- add `proxiesCount` publication
- use `proxiesCount` publication to control item visibility
  - navigation menu `proxyIsConfigured` helper
  - API view `proxyIsConfigured` helper

### CODE REVIEW

**Comment by brylie** [comment]
@apinf/developers please review

Ping @bajiat

**Comment by bajiat** [comment]
@frenchbread  Would you be available reviewing this PR ? Does not have to happen today, Monday is still ok.

**Comment by bajiat** [comment]
Reassigned the task to @jykae

**Comment by jykae** [comment]
Reviewing

**Comment by jykae** [comment]
@brylie Onclick "add proxy":
nayttokuva 2016-09-20 kello 12 07 10

nayttokuva 2016-09-20 kello 12 08 23

**Comment by brylie** [comment]
@jykae please review. I added a fix for the #add-proxy event handler.

**Comment by jykae** [comment]
Form opened, but next one:
nayttokuva 2016-09-20 kello 13 06 49

And closer look:
nayttokuva 2016-09-20 kello 13 07 08

**Comment by brylie** [comment]
@jykae I added a check for `instance.data`. Please review.

**Comment by jykae** [comment]
@brylie please eslint also your code

nayttokuva 2016-09-20 kello 16 11 12

**Comment by brylie** [comment]
@jykae I linted the proxies.js file. Please review.

**Comment by jykae** [comment]
Cool, were done here :)

**Pull request merged**
