### PR TITLE
IE: Mail settings can't be saved as SMTP Port field doesn't recognize

### LINKED ISSUE #3270: IE: Mail settings can't be saved as SMTP Port field doesn't recognize numeric value
**Steps to Reproduce**: 
1. go to page: https://vamos.apinf.io and login as admin
2. go to user>settings
3. Enable Email settings, provide necessary and valid values to the fields and click Save
                    
**Outcome**:
SMTP Port field is highlighted and shows alert message: "SMTP Port number must be a number", despite numeric value is provided in the field.
In other browsers (e.g. chrome, FF) the field appears as controller to add numeric values using up/down arrows. 
However, in IE11, the controller doesn't appear.
image
         
**Expected Behavior**:
It should be possible to save valid field value.
Controller to add numeric values in a field should appear properly.
                   
**Environment**:
Windows 10, IE11, APInf vamos site (https://vamos.apinf.io) - Release 0.52

### PR DESCRIPTION
**Pull request by deligence-dharmendra**
Closes #3270

## Changes

- change in settings.html
- add custom input type in the auto form quick field

## Developer checklist
This checklist is to be completed by the PR developer:

- [ ] Alternative solutions were compared/discussed before writing code
    - [ ] trade-offs with this solution are considered acceptable
- [ ] Code in this PR adheres to the [project styleguide](CONTRIBUTING.md)
- [ ] This pull request does not decrease project test coverage
- [ ] If the code changes existing database collection(s), migration has been written
- [ ] If UI texts are added or changed, all texts are internationalized

## Reviewer checklist
Reviewed by: @matleppa @marla-singer 

This list is to be completed by the pull request reviewer:
- [ ] Code works as described/expected
- [ ] Code seems to be error free
    - [ ] no browser console errors visible
    - [ ] no server console errors visible
    - [ ] passes CI build
- [ ] Code is written in a way that promotes maintainability
    - [ ] easy to understand
    - [ ] well organized
    - [ ] follows project coding standards and conventions
    - [ ] well documented

### CODE REVIEW

**Comment by deligence-dharmendra** [comment]
Hi @marla-singer @matleppa, I have tested the issue in my development environment. It working good with IE 11 and Windows 10 (before and after changes).

But I have seen the same issue in Branding (Overlay transparency) and EMQ add proxy form.
I think it is due to schema define input type number. I'm just guessing. I'm not sure.So that I want to test changes in **https://nightly.apinf.io/** environment.
**Environment:** Development, Windows 10, IE 11.

Please find the attached some screenshot.
imgpsh_fullsize 3
imgpsh_fullsize 4
imgpsh_fullsize 5

**Comment by marla-singer** [comment]
@deligence-dharmendra Okay, let's check this fix on nightly environment

**Comment by deligence-dharmendra** [comment]
@marla-singer  Ok thanks. let me know once it deployed in the nightly environment. So I will confirm.

**Comment by marla-singer** [comment]
@deligence-dharmendra The nightly environment has updated code. Please check if the fix works

**Comment by deligence-dharmendra** [comment]
@marla-singer Currently its working fine on the nightly environment.

**Comment by marla-singer** [comment]
@deligence-dharmendra Great. I gonna create a new issue to resolve the same bug for other fields that you found and assign it to you

**Comment by deligence-dharmendra** [comment]
@marla-singer Ok

**Pull request merged**
