### PR TITLE
Feature/updated navbar

### LINKED ISSUE #2371: Title bar and navbar
# User story

# Goal
* Both title bar and navbar should be sticky
* Keep in mind mobile-first approach
* Title bar should contain the logo and the Sign in link. Remove language selection. (Language selection to be moved to footer in separate issue.)
Navbar
  * Anonymous user should be able to go to Catalog or Manage APIs from navbar
    * Open issue: Where shoud Manage APIs lead to: additional information for manager + sign in or sign in and Add API
  * About should be removed from the navbar for both anonymous and signed-in user (Separate issue to add About to footer)

# Wireframe
laptop view
frontpage1-3
<br></br>
<br></br>
mobile view
mobile1

### PR DESCRIPTION
**Pull request by nnn**
Closes #2371

Updated navigation for phones/tablets.
Please, use your device or browser device toolbar/inspector to test it on different screens.

### CODE REVIEW

**Comment by bajiat** [comment]
@marla-singer Would you have time to review?

**Comment by marla-singer** [comment]
@bajiat Sure

**Comment by marla-singer** [comment]
@nnn I tested in Safari browser, iOS 10.2
1. add attribute `maximum-scale=1.0` for `<meta name="viewport">`. 
2. User menu doesn't work as expected

**Comment by nnn** [comment]
@marla-singer will check the Safari tomorrow, don't have iOS device now to test on.

> add attribute maximum-scale=1.0 for <meta name="viewport">

`maximum-scale=1.0 `it's bad news for accessibility, since it won’t allow the user to zoom, so would avoid this.

**Comment by marla-singer** [comment]
@nnn Tested using Android device.
Yes, `maximum-scale=1.0` is bad for Android but good for iOS
Without this attribute, markup feels bad when I navigate to Sing In (Sing Up) page and hide the keyboard
image
image 1

**Comment by nnn** [comment]
@marla-singer please check now.

**Comment by marla-singer** [comment]
@nnn Good 👍

**Comment by brylie** [comment]
I agree that maximum-scale is not a great solution, since it doesn't allow zooming. This hurts accessibility.

**Comment by nnn** [comment]
Fixed that bug in Safari. @marla-singer please review, as soon as possible, let's try to merge this today.

**Pull request merged**
