### PR TITLE
Feature/reorganize packages

### LINKED ISSUE #2810: Move all APInf packages' into /apinf_packages directory
Our project structure is currently very flat, with the top level containing many directories. This can be a bit disorienting when first glancing the source code.

# Goal
Make the source code easier to understand by combining all project 'modules' under one directory.

- /
  - .meteor
  - .scripts
  - core/
  - docker/
  - apinf_packages/
    - apis/
    - branding/
    - catalog/
    - ...

  - tests/
- README.md
- ...

### PR DESCRIPTION
**Pull request by brylie**
Closes #2810 

# Changes
- remove 'packages' from `.gitignore`
- move all APInf 'packages' into `packages/` directory

**TODO**: fix all imports
**TODO**: test application

### CODE REVIEW

**Comment by mauriciovieira** [comment]
@brylie I did some _sed magic_ to fix the imports, but did not test the application.

@matleppa @marla-singer can you review to spot anything we missed?

**Comment by bajiat** [comment]
@marla-singer Is it ok for you to review this?

**Comment by marla-singer** [comment]
@mauriciovieira @brylie
The path to regex.js file is correct. And I don't know why it happens but my feeling is that the application doesn't have incorrect structure. Because of `core/` folder is upper than `packages/` folder when it runs earlier and can't find files from folder `packages/`
https://guide.meteor.com/structure.html#load-order

**Comment by brylie** [comment]
It might be because the import statement is located in `/core/lib/simple_schema_config.js`. Anything in a `lib` folder is loaded before other application code. 

I think the change here would be to move those proxy-specific `SimpleSchema.messages` into the `proxy` module:

```
SimpleSchema.messages({
  regEx: [
    // TODO: define custom mesages for every RegEx
    { exp: proxyBasePathRegEx, msg: invalidProxyBasePathMessage },
    { exp: apiBasePathRegEx, msg: invalidApiBasePathMessage },
    { exp: contactPhone, msg: invalidContactPhoneMessage },
```

**Comment by marla-singer** [comment]
@brylie Try and you will see after that it throws an error in folder `migrations/server/..`. :confused:

**Comment by brylie** [comment]
Is it a related error, or just something else that needs to be fixed?

**Comment by marla-singer** [comment]
> Is it a related error, or just something else that needs to be fixed?

The error is related to import error.

**Comment by brylie** [comment]
Right, but is it related to the Simple Schema messages?

We realize that we are going to have to work through some errors. I am trying to figure out how to solve the errors one at a time.

**Comment by brylie** [comment]
OK, the regex error seems to be resolved.

The next error I encounter is:

```js
 Error: Cannot find module '/packages/proxies/collection'
     at Function.require.resolve (packages/modules-runtime.js:145:19)
     at Module.resolve (packages/modules-runtime.js:95:25)
     at Module.Mp.importSync (/home/brylie/.meteor/packages/modules/.0.8.2.1mxo6wg++os+web.browser+web.cordova/npm/node_modules/reify/lib/runtime.js:74:27)
     at meteorInstall.core.migrations.server.1-move-proxy-settings.js (core/migrations/server/1-move-proxy-settings.js:1:125)
     at fileEvaluate (packages/modules-runtime.js:197:9)
     at require (packages/modules-runtime.js:120:16)
     at /home/brylie/code/Apinf/platform/.meteor/local/build/programs/server/app/app.js:913:1
     at /home/brylie/code/Apinf/platform/.meteor/local/build/programs/server/boot.js:303:34
     at Array.forEach (native)
     at Function._.each._.forEach (/home/brylie/.meteor/packages/meteor-tool/.1.4.4_2.cfbjtd++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
     at /home/brylie/code/Apinf/platform/.meteor/local/build/programs/server/boot.js:128:5
     at /home/brylie/code/Apinf/platform/.meteor/local/build/programs/server/boot.js:352:5
     at Function.run (/home/brylie/code/Apinf/platform/.meteor/local/build/programs/server/profile.js:510:12)
     at /home/brylie/code/Apinf/platform/.meteor/local/build/programs/server/boot.js:351:11
```

**Comment by brylie** [comment]
> Because of core/ folder is upper than packages/ folder when it runs earlier and can't find files from folder packages/
https://guide.meteor.com/structure.html#load-order

What can we rename 'core' to avoid this problem? What is an alternative solution?

Right now, I am stuck on the `/core/migrations/` folder, where it needs to import from directories after `core` alphabetically.

**Comment by brylie** [comment]
Perhaps we could rename the `packages` directory to `imports`? We would have to make sure we are using explicit imports in all files.

**Comment by marla-singer** [comment]
> **imports**
Any directory named imports/ is not loaded anywhere and files must be imported using import.

Would we not have more problems with `imports/` folder? :thinking:

**Comment by brylie** [comment]
Well, I am not sure how to measure how many problems we would have with *packages*  to compare the number of problems we would have with *imports*.

I do have a local experimental branch where I have renamed *core* to *main* and *packages* to *imports*. I will work through a few more errors, but for now things seem to be working after fixing import paths.

**Comment by brylie** [comment]
With the above approach, renaming *packages* to *imports*, we will just have to be explicit about all of our imports.

**Comment by brylie** [comment]
OK, try the branch now. The strategy seemed to work:

- **core** --> **main**
- **packages** --> **imports**

**Comment by brylie** [comment]
Dang it. I am now getting the following client error:

```
There is no route for the path: /
```

**Comment by brylie** [comment]
Hm, it seems that FlowRouter doesn't like the project structure. I'm at a loss as to what to do. @marla-singer @mauriciovieira any ideas?

**Comment by marla-singer** [comment]
@brylie Attention on Travic-CI log:
```
/home/travis/build/apinf/platform/imports/api_docs/client/swagger_ui/content/content.js
  15:21  error  Unable to resolve path to module '/packages/api_keys/collection'  import/no-unresolved
/home/travis/build/apinf/platform/imports/api_docs/client/view/resumable.js
  19:30  error  Unable to resolve path to module '/core/helper_functions/file_name_ends_with'  import/no-unresolved
/home/travis/build/apinf/platform/imports/api_keys/client/api_key.js
  13:21  error  Unable to resolve path to module '/packages/api_keys/collection'  import/no-unresolved
/home/travis/build/apinf/platform/imports/api_keys/collection/server/publications.js
  5:21  error  Unable to resolve path to module '/packages/api_keys/collection'  import/no-unresolved
/home/travis/build/apinf/platform/imports/api_keys/server/methods.js
  9:21  error  Unable to resolve path to module '/packages/api_keys/collection'  import/no-unresolved
/home/travis/build/apinf/platform/imports/apis/client/card/apiCardPin/api_card_pin.js
  12:27  error  Unable to resolve path to module '/packages/organizations/collection'  import/no-unresolved
/home/travis/build/apinf/platform/imports/apis/client/profile/details/details.js
  14:21  error  Unable to resolve path to module '/packages/api_keys/collection'  import/no-unresolved
/home/travis/build/apinf/platform/imports/apis/client/profile/view.js
  16:22  error  Unable to resolve path to module '/packages/feedback/collection'  import/no-unresolved
```

I don't know. Replace `home/` folder to `main`?

**Comment by mauriciovieira** [comment]
@brylie why not put the core inside packages?

@brylie @marla-singer My hypothesis now is that meteor requires anything inside _packages_ directory to have a package definition file `packages.js`. For a reference, take a look at all directories inside Rocket.Chat/packages, like [Rocket.Chat Analytics](https://github.com/RocketChat/Rocket.Chat/tree/develop/packages/rocketchat-analytics)

**Comment by brylie** [comment]
> meteor requires anything inside packages directory to have a package definition file packages.js.

@saransh-dev has also pointed this out in chat. Thanks to both of you :-) We can start defining the package.js in all of the packages, which seems like a good step towards the goal of being able to publish these packages on NPM.

**Comment by brylie** [comment]
> @brylie why not put the core inside packages?

Great suggestion. I will work on this today.

**Pull request closed without merging**
