### PR TITLE
issue fixed Organization card: Misaligment elements #2939

### PR DESCRIPTION
**Pull request by saransh-dev**
# Fixed issue #2939 

Closes: #2939

### CODE REVIEW

**Comment by marla-singer** [comment]
joxi_screenshot_1506424730515

**Comment by brylie** [comment]
Perhaps just put the 'days ago' text and 'apis count' on their own row, so we don't have to wrestle with this issue. That way, they will always be stacked, regardless of locale.

**Comment by marla-singer** [comment]
@brylie Or we can use CSS style to "hidden" part
joxi_screenshot_1506425374399

**Comment by saransh-dev** [comment]
We can do one thing that if text length larger then specific limit then we can convert text like some part of that text + .... 
text is limit is 15 characters then,
Text:- `Lisatty 15 paivaa sitten`
then it will be `Lisatty 15 paiv...`

Please advise.

**Comment by marla-singer** [comment]
> We can do one thing that if text length larger then specific limit then we can convert text like some part of that text + ....
text is limit is 15 characters then,
Text:- Lisatty 15 paivaa sitten
then it will be Lisatty 15 paiv...

@saransh-dev Awful. 
1. As I said above you must use CSS --> https://www.w3schools.com/cssref/css3_pr_text-overflow.asp
2. If your CSS skill doesn't allow you manipulate with text then remove "Added" world as we have in API catalog.

**Comment by marla-singer** [comment]
@saransh-dev Squash your commits into one

**Comment by brylie** [comment]
@marla-singer we don't have a mandate to squash commits here.

**Comment by marla-singer** [comment]
@saransh-dev Awesome :confetti_ball:

**Pull request merged**
