### PR TITLE
feature/update-api-apiumbrella

### LINKED ISSUE #1510: Edit Proxy backend and store the changes in API Umbrella
If user edits the Proxy backend settings in te Proxies tab in API profile view, the changes will need to be reflected in API Umbrella.

# Definition of done
* [x] The edited proxy backend data/settings gets properly updated in API Umbrella

### PR DESCRIPTION
**Pull request by nnn**
Closes #1510

### CODE REVIEW

**Comment by marla-singer** [comment]
@nnn Is it ready for review? Please use the label 'Ready for review' to make it clear when a PR is ready.

**Comment by frenchbread** [comment]
Code looks good! Was not able to verify while testing though. Updated API on local Apinf and it was not updated on API Umbrella. @brylie have you been able to test?

**Comment by brylie** [comment]
@frenchbread yes, I was able to test and demonstrated for @bajiat. Try doing a `meteor reset` perhaps? Did you see any console errors?

**Comment by frenchbread** [comment]
@brylie There are no any console errors. 

Form cannot finish submit ("Publish" button is disabled & nothing happens). Sometimes form finishes submit & throws a success message, but still, updates are not reflected on API Umbrella.

**Comment by frenchbread** [comment]
@jykae Could you please test it & verify that is works? Then we could merge this sooner.

**Comment by jykae** [comment]
@frenchbread I could check this today afternoon

**Comment by jykae** [comment]
Reviewing

**Comment by jykae** [comment]
Insert & update both work, tested with "nightly.apinf.io" Umbrella.

**Pull request merged**
