### PR TITLE
Require essential proxybackend fields

### LINKED ISSUE #1562: User not notified if details missing/invalid while saving the proxy settings
Steps:  
1.Visit https://nightly.apinf.io    
2.Create account clicking on 'Sign up'     
3.Add API Backend      
  - Enter API name    
  - Click on 'Add API'    

4.Go to 'Catalog' and click on 'My APIs' tab     
5.Click on API added above      
6.Click on 'Proxy'   
    - Enter invalid proxy base path / keep the text field empty   
    - Enter API base path (eg. / )   

7.Click on 'Save proxy settings' button    
8.Go to 'Details' view  

Findings:  
- Successful in saving proxy settings    
- User not notified if details are invalid/missing  
- Details view gets updated showing Base URL with text  'undefined '    

Expected Result: User must be notified if details are missing/invalid while saving proxy settings.   

Browser:    
Mozilla Firefox 48.0 
(Mozilla Firefox for Ubuntu Canonical – 1.0 )   

Operating System:    
Ubuntu 16.0 LTS     

Screenshot:  
add_api_no_proxypath    

base_url_undefined

### LINKED ISSUE #1816: ProxyBackend form notification, if form is not filled at all
Found by @marla-singer in PR #1806 

Steps:
1. Go to any API and open Proxy tab
2. Click on Delete button, if there are any information
3. Don't fill a form and click on Save&Publish button

Found result: Submit hook isn't end, button is disable, no one notification about required fields
Expected result: Notify users about required fields and button must be available

### PR DESCRIPTION
**Pull request by jykae**
Closes #1562 
Closes #1816 

- require essential proxybackend fields, regex validation kicks in only when field has some input

### CODE REVIEW

**Comment by marla-singer** [comment]
@jykae Notification worked before too. I detected another problem and required fields don't resolve it.
Steps:
1. Go to any API and open Proxy tab
2. Click on Delete button, if there are any information
3. Don't fill a form and click on Save&Publish button

**Found result:** Submit hook isn't end, button is disable, no one notification about required fields
**Expected result:** Notify users about required fields and button must be available

Should I create another issue or you will fix in this repo?

**Comment by jykae** [comment]
@marla-singer good find, I'll check after lunch 🍽

**Comment by jykae** [comment]
There is open issue on autoform about this https://github.com/aldeed/meteor-autoform/issues/1442 I try to call that validateForm if it makes any difference, as @abecks suggests so.

**Comment by marla-singer** [comment]
@jykae I had the same situation when worked on monitoring feature. I did the handle check on insert/update hook
https://github.com/apinf/platform/blob/develop/monitoring/client/autoform.js#L16

**Comment by jykae** [comment]
@marla-singer Well, it's not beauty but I think it checks now all "required" fields have values. Maybe I should add star for required field labels in addition to showing error message.

**Comment by jykae** [comment]
@marla-singer could you check if this fixes now issue with empty fields? I would like to leave the star issue as enhancement, I don't know that much of CSS magic.

**Comment by marla-singer** [comment]
@jykae Works :+1: I couldn't merge it because of console log in code so I afforded to delete it

**Comment by jykae** [comment]
@marla-singer 🆒 and thanks for contribution 🎉

**Pull request merged**
