### PR TITLE
New visibility feature

### LINKED ISSUE #1624: Visibility of API that is private for a user group
# Definition of done
* [x] If the API is visible to a group, only those people can 
  * [x] see the API in the catalog
  * [x] see the API profile page
* [x] If an unauthorized user has the direct link to the API profile, they must see a 403 .

# Wireframe

1. API Catalog Card View
apicatalogprivate

2. API Catalog table View
apicatalogtableprivate

In both cases, Users having access to Private API should be able to see them in API Catalog.
Respective Card & Table will contain a tag named Private.
Public APIs should not have any tags

3. API profile view
apiprofileprivate

 Tag should appear beside API name.
Should be larger in size than card/table view

### LINKED ISSUE #1686: Administrators cannot see private APIs when not in the managers list
Originally reported by @marla-singer in #1669 

Right now, Apinf admin users **can't see private APIs**

# Screenshots

1. User is Apinf Administrator. Catalog has 4 apis
joxi_screenshot_1475577095313

2. Log in like one of api owner. Set api as private
joxi_screenshot_1475577239491

3. Log in like Apinf administrator. Catalog has 3 apis
joxi_screenshot_1475577184490

### PR DESCRIPTION
**Pull request by jykae**
Closes #1624 
Closes #1673 (work by @nnn included)
Closes #1686

### CODE REVIEW

**Comment by bajiat** [comment]
@marla-singer Would you be interested in mentoring Ville and reviewing the PR when it's ready for review? Do you have time in addition to finishing the monitoring task?

**Comment by marla-singer** [comment]
@bajiat Yes, I have time to finish my task and mentoring

**Comment by jykae** [comment]
I think this is ready for review. Public & Private visibility settings should work. Semipublic is not here yet.
Visibility checks for public, private settings should be in place.
In catalogue/API profile we show "private" indicator tag when API is private/semipublic

@brylie I have added initial visibility checks to check "authorizedUserIds" array in catalogue publication, however we'll need to check they work after your PR #1623 is ready, and we have UI for giving view permissions to users. You can continue to this PR if you like.

**Comment by jykae** [comment]
@marla-singer ready for review, don't merge yet, semipublic is partial feature. To be implemented in #1623

**Comment by brylie** [comment]
@jykae see PR #1704 for work in progress. Right now, the form adds the user ID to the `authorizedUserIds` array, so you can get an idea of how things work.

**Comment by jykae** [comment]
ok, thanks for mentoring @brylie I try out that authorizedUserIds check for catalogue before review using meteor shell to add userIds to array.
@marla-singer I take out review tag, and add it back if it works as expected.

**Comment by jykae** [comment]
@marla-singer added couple of checks related to bookmarks filter. Now ready for review.

**Comment by marla-singer** [comment]
Reviewing

**Comment by marla-singer** [comment]
Well, the tag system works good :+1:

**Comment by marla-singer** [comment]
@jykae Well, the tag system works good :+1:

**Comment by jykae** [comment]
Ok, cool. I include migration code for new fields for visibility. We can probably merge this after that.

**Comment by jykae** [comment]
@marla-singer had a chat with @brylie about #1704 we don't need change isPublic field when we have authorizedUserIds array. I make changes to align our efforts.

**Comment by jykae** [comment]
Please close when #1718 gets merged, replaces this one.

**Comment by brylie** [comment]
Closing, since newer PR is in progress.

**Pull request closed without merging**
