### PR TITLE
Feature/updated api card

### LINKED ISSUE #1732: Catalog: for API with large description texts, make words from 3rd sentence appear in fading color
This would give the appearance of more details that is available to view from API profile.
image

### LINKED ISSUE #1757: API card: the Private label and api description look bad and unreadable together
Verified on staging
When the api description is big and visibility is private, API card layout looks bad and unreadable

**Steps**:
1. Create an api with big description
2. Make it Private
3. Go to Catalog

**Found**: 

joxi_screenshot_1476182360576

### LINKED ISSUE #1785: If title exceeds one line, an extra line appear on catalog card

### LINKED ISSUE #2315: In organization view, API names cut off
## Current outcome
In organization view https://apinf.io/organizations/tm-forum-ecosystem API names in cards are cut off. This is not acceptable. 
tmforum

## Expected outcome
API names are presented as they are given by the owner.

### LINKED ISSUE #2342: Re-design the API card so that logo shapes can be preserved
Re-design the API card so that logo shapes can be preserved. Maximum height and width needs to be defined, though.

### Definition of done
- [x] Create the new style for API card and reviewed it

### PR DESCRIPTION
**Pull request by nnn**
Closes #2342 
Closes #2315 
Closes #1785 
Closes #1757 
Closes #1732
Includes updated API card
Need to be confirmed before applying changes to organisation card.

### CODE REVIEW

**Comment by nnn** [comment]
Got some feedbacks from @Nazarah and @bajiat.
@marla-singer I am finishing this task today later in the evening.
Soon will be ready for code review. Please review, if you are available.

**Comment by nnn** [comment]
@marla-singer please review, if you are not available, @apinf/developers.

**Comment by marla-singer** [comment]
@nnn Take it

**Comment by marla-singer** [comment]
@nnn Misaligned `created_at` data in Suomi view. 
joxi_screenshot_1491203300794

**Comment by nnn** [comment]
@marla-singer fixed.

**Comment by marla-singer** [comment]
@nnn Good. You did the one part of issue. I suggest to not close the current issue. I created the Definition of Done and checked that style has for API card. Is it Ok?

**Comment by nnn** [comment]
@marla-singer I really don't want to do it, I mean creating a generic style for both cards.
What I have noticed is that API card and Organizartion card should be treated differently, b/ they are about different things. 
My proposal here is that we update the definition of done to match current PR (API card only).
Create a separate task for this Sprint to re-structure/re-design Organization card. Assigned it to me (I will estimate it 1 day).

ping @bajiat

**Comment by bajiat** [comment]
Go ahead with API card

**Comment by marla-singer** [comment]
@nnn Please create the separate issue

**Comment by nnn** [comment]
@marla-singer I updated the definition of done of the original issue to match current PR (API card only). I created a separate PR for the Organization card enhancements.

**Comment by bajiat** [comment]
Could we move the "X days ago" since the length varies? Could it be on a row below? 

Also note that the pinning function could go there with bookmarking and star rate. Refer to issue #2311

**Comment by nnn** [comment]
@bajiat  Yes, got the same idea yestrerday, but it will take some time so can this be an future enhancement?

**Comment by nnn** [comment]
@marla-singer as discussed with @bajiat I will move

> Could we move the "X days ago" since the length varies? Could it be on a row below?

to a separate issue.

Please, go ahead and merge if don't have other suggestions.

**Comment by marla-singer** [comment]
@nnn Please create this issue. I merge it

**Pull request merged**
