### PR TITLE
Ensure API document is available before returning name

### LINKED ISSUE #2528: apinf.io dashboard empty
# Steps to reproduce
1. Log into apinf.io (as admin user)
2. Go to dashboard

# Result

production dashboard empty 0 43 0

Console error:
```
TypeError: Cannot read property 'name' of undefined
  at e.apiName (https://apinf.io/bb2540909451ddaee73743b11b0dac9549b8624d.js?meteor_js_resource=true:449:24269)
  at https://apinf.io/bb2540909451ddaee73743b11b0dac9549b8624d.js?meteor_js_resource=true:448:22152
  at h (https://apinf.io/bb2540909451ddaee73743b11b0dac9549b8624d.js?meteor_js_resource=true:17:22322)
  at Function.ys [as map] (https://apinf.io/bb2540909451ddaee73743b11b0dac9549b8624d.js?meteor_js_resource=true:18:31451)
  at Object.proxyBackends (https://apinf.io/bb2540909451ddaee73743b11b0dac9549b8624d.js?meteor_js_resource=true:448:22115)
  at https://apinf.io/bb2540909451ddaee73743b11b0dac9549b8624d.js?meteor_js_resource=true:153:31360
  at https://apinf.io/bb2540909451ddaee73743b11b0dac9549b8624d.js?meteor_js_resource=true:153:17194
  at https://apinf.io/bb2540909451ddaee73743b11b0dac9549b8624d.js?meteor_js_resource=true:153:31993
  at Function.e._withTemplateInstanceFunc (https://apinf.io/bb2540909451ddaee73743b11b0dac9549b8624d.js?meteor_js_resource=true:154:5707)
  at https://apinf.io/bb2540909451ddaee73743b11b0dac9549b8624d.js?meteor_js_resource=true:153:31900
bb25409….js?meteor_js_resource=true:3 Connection timeout. No sockjs heartbeat received. 
```

### PR DESCRIPTION
**Pull request by brylie**
Closes #2528 

Note, we will need to make a new patch-level release for this hotfix.

### CODE REVIEW

**Comment by marla-singer** [comment]
@brylie It is a little fix but I'm afraid that is not a solution of entire problem. Please make sure that removing API document with Proxy connection works as expected (related Proxy Backend is removed aswell)

**Comment by bajiat** [comment]
@marla-singer Can I assign you to this PR?

**Comment by marla-singer** [comment]
@bajiat Yes

**Comment by brylie** [comment]
Don't merge yet.

**Comment by brylie** [comment]
@bajiat should we release this as a 0.43.1 or 0.44.1 patch? If we want to make it available quickly, we discussed that 0.43.1 is better than 0.44.1. Otherwise, if we plan to upgrade customer deployments soon with 0.44.x, then 0.44.1 would be alright.

**Comment by marla-singer** [comment]
@brylie What status of this PR?

**Comment by brylie** [comment]
I think at this point we should target the PR for 0.44.1, so we can finish the work. 

cc: @bajiat

**Comment by bajiat** [comment]
At this point it should be 44.1

**Comment by marla-singer** [comment]
@brylie Are you sure that we need to merge it directly to master branch? In this case `develop` will differ from `master`

**Comment by brylie** [comment]
@mauriciovieira, @ashakunt, @kumargs: If we merge this branch in to `master`, for the 0.44.1 patch level release, how should we also merge this change into `develop`?

**Comment by brylie** [comment]
> @brylie Are you sure that we need to merge it directly to master branch? In this case develop will differ from master

@marla-singer I dont know exactly what steps to take. The [Gitflow diagram](http://nvie.com/img/git-model@2x.png) shows 'hotfix' branches being opened against `master`. Also, my [Gitflow tool](https://github.com/petervanderdoes/gitflow-avh/blob/develop/README.md) opens 'hotfix*' branches against `master`, so I just followed those guidelines.

**Comment by marla-singer** [comment]
@brylie Can you test it local?
Maybe rebase is a litlle bit bad because `rebase` changes commit tree.
Gitflow diagram also has notice "Incorporate bugfix in develop"

**Comment by brylie** [comment]
I just re-read the instructions you mentioned. We can merge this PR and then I will run the following commands:

```bash
$ git checkout develop
Switched to branch 'develop'
$ git merge --no-ff myfeature
Updating ea1b82a..05e9557
(Summary of changes)
$ git branch -d myfeature
Deleted branch myfeature (was 05e9557).
$ git push origin develop
```

**Comment by marla-singer** [comment]
@brylie ok, let's try

**Pull request merged**
