### PR TITLE
Lint monitoring directory

### PR DESCRIPTION
**Pull request by mauriciovieira**
This PR is part of #2045 endeavor.

### CODE REVIEW

**Comment by mauriciovieira** [comment]
@apinf/developers please review

**Comment by brylie** [comment]
@marla-singer can we delete this branch now that it is merged?

**Comment by marla-singer** [comment]
@brylie Nope. @jawidahmadi wrote me that he has the error on his side.

**Comment by marla-singer** [comment]
@brylie Can you please run this PR and check if you have any problem with running?

**Comment by marla-singer** [comment]
@brylie Everything is fine. Delete branch

**Comment by brylie** [comment]
@marla-singer ok.

**Pull request merged**
