### PR TITLE
Topbar search field fix

### LINKED ISSUE #2015: On using topbar search option once, it can't be used again from other pages unless page is reloaded.
# Reproduction Steps:

1. go to nightly.apinf.io
2. Click on Search icon on Top bar
3. Type a keyword and click Search.
4. Go to another page from Search page..
5. Click on Search icon on Topbar.

# Result
Searchbar doesn't appear on topbar.
Page needs to be reloaded for the searchbar to appear.
tobarsearch

# Expected Result
In Search page, the search icon should appear on Topbar
On performing a search using topbar, it should be possible to reuse the option without page reload.

# Environment
Windows 8, Chrome

### PR DESCRIPTION
**Pull request by nnn**
Closes #2015

### CODE REVIEW

**Comment by marla-singer** [comment]
@nnn What does it resolve? The 
joxi_screenshot_1486470068869 icon doesn't appear after searching

**Comment by marla-singer** [comment]
joxi_screenshot_1486470120899

**Comment by marla-singer** [comment]
Although as for me the Search page doesn't need this icon

**Comment by nnn** [comment]
It designed this way. We should have only one search field on a page.
When user is on the search results page, an icon in the search field is hidden.

Fix is for search field doesn't appear if you go anywhere from search result page and try to click a search icon (see Nazia's GIF attached).

**Comment by marla-singer** [comment]
@nnn Okay, I see the problem

**Pull request merged**
