### PR TITLE
New Swagger

### LINKED ISSUE #2349: Upgrade Swagger UI to 3.x
Swagger UI 3.x was released on 2017-03-19. We should consider upgrading to the recent release ASAP, for improved features and possibly stability.

- https://www.npmjs.com/package/swagger-ui

# Related
#2211 - swagger UI documentation sections not expanding

## Upstream
- [Ampersand character being escaped in rendered documentation](https://github.com/swagger-api/swagger-ui/issues/2700)

### LINKED ISSUE #2487: Generate SDK file displays error
# Steps  
1.Visit https://staging.apinf.io v 0.43.0 
2.Login 
3.Add API and connect it to proxy  (eg. staging/API-umbrella New)
4.Go to above added API   
5.Click on 'Documentation' tab 
6.Upload documentation file (eg.swagger.yaml)  
7.Go to 'SDK Generate'  
8.Select any language 
9.Click on 'Download'  

# Findings 
- API documentation view shows  a 'warning' message  
- Generate SDK file shows error "File not supported by Code Generator....."     

# Screenshot 
upload_documentation_file_info_warning       

generate_sdk_file_error_msg1

### PR DESCRIPTION
**Pull request by marla-singer**
Closes #2349 
Closes #2487 
Codegen didn't work because we change the method of getting URL documentation

### CODE REVIEW

**Comment by marla-singer** [comment]
@brylie  Ready for review

**Comment by bajiat** [comment]
@marla-singer This PR has escaped our radar. is it still a valid fix?

**Comment by marla-singer** [comment]
@bajiat nightly and staging have a new Swagger UI but without additional features. I opened issue about that (#2504)

**Comment by bajiat** [comment]
This was connected to #2487. Is that solved or should we remove the reference to it?

**Comment by marla-singer** [comment]
Should remove. I hoped that it will fix

**Comment by brylie** [comment]
Done.

**Pull request merged**
