### PR TITLE
Add the new conditions and phrases for usage instruction

### LINKED ISSUE #1759: API Details: the wrong description in usage instruction if "Disable API key" is true
Verified on staging.
If an api owner sets "Disable API key" true, the usage instruction should be update. Now it isn't so.

**Steps**:

1. Create an api and go to Proxy tab
2. Fill up the form "Proxy backend configuration", also check "Disable API key"
3. Get API key, if you don't have yet
3. Go to Details tab

**Found**: 
Usage instraction has the next:
"call the API **with your key** in the URL parameters: ..."
"call the API **with your key** in the request headers: ..."
joxi_screenshot_1476187321127

**Expected**: 
Users can "call this API without an API key." Because the feature "Disable API key" in Proxy tab means that

### LINKED ISSUE #1762: Enable 'API key requirement' allows Call API without API Key
# Steps
1. Visit https://staging.apinf.io  
2. Login    
3. Add API Backend    
    -  Enter Name  
    -  Enter Description  
    -  Enter URL  
4. Go to Proxy  
5. Enter proxy configuration details   
6. Select option 'Disable API key requirement'  and Save   
7. Go to API Details view    
8. Do not 'Get API key'  
9. Call API : click  on URL in usage instructions  (URL without API key)    
10. Go to 'Proxy'  
11. Enable API Key requirement      
12. Click on 'Save&Publish'    
13. Call API :  click on URL in usage instructions  (URL without API Key)     

# Expected Result 
Call API  without API key should be unsuccessful    
  
# Actual Result 
Call API without API Key was successful while 'enabled API Key requirement '    

# Browser
1. Mozilla Firefox 48.0 
2. Google Chrome 52.0.2743.116     

# Operating System
Ubuntu 16.0 LTS

### PR DESCRIPTION
**Pull request by marla-singer**
Closes #1759 
Closes #1762

### Implemented the scenario:
1. If Proxy backend configuration is completed, "Disable API key" is false and user haven't got api key yet, usage instruction has message as "use your API key. Click the "Get API key" button to request the key"

2. If Proxy backend configuration is completed, "Disable API key" is false and user has got api key, usage instruction has message as  "use your API key in the URL parameters or in the request headers"

3. If Proxy backend configuration is completed, "Disable API key" is true, usage instruction has message as  "use the URL"

### CODE REVIEW

**Comment by marla-singer** [comment]
@brylie Could you please review it?

**Comment by jykae** [comment]
Reviewing

**Comment by jykae** [comment]
@marla-singer works as described, what you think, could API key itself be also hidden from API view if "Disable API key requirement" is true for API? It could probably done easily with your new helpers.
nayttokuva 2016-10-26 kello 9 02 25

**Comment by jykae** [comment]
@marla-singer We discussed this in daily, I merge this one and we'll do above thing if we get user feedback about it.

**Pull request merged**
