### PR TITLE
Complete publication execution

### LINKED ISSUE #1565: Anonymous user unable to view API details from homepage or Catalog view
Steps:  
1.Visit https://nightly.apinf.io  
2.Click on 'Catalog'  
3.Select and click on API 

Actual Result: Shows empty page with spinner rotating indefinitely  
Expected Result : Selected API details must be available for the anonymous users. 

Browser: Google Chrome 52.0.2743.116

Operating System: Ubuntu 16.0 LTS  

Screenshot:  
empty_api_view

### LINKED ISSUE #1605: Users can't view non-owner api
Users can't view the api page, which they are not the owners. Is it bug or feature?

Step to reproduce:
1. Create the new user without administrator roles
2. Go to [https://nightly.apinf.io/api/AfYunEcjD3QaEb5D7](my api view)

Found result: Spinner always switch on and api view isn't showed

Expected Result: Api view must be showed

### PR DESCRIPTION
**Pull request by frenchbread**
Closes #1565 
Closes #1605

### CODE REVIEW

**Comment by frenchbread** [comment]
@marla-singer Could you please review & verify?

**Comment by marla-singer** [comment]
@frenchbread Yes. I'll start it on Monday

**Comment by marla-singer** [comment]
@frenchbread #1565 works right. But #1605  is still not.

**Comment by frenchbread** [comment]
@marla-singer Pushed changes, please check now.

**Comment by brylie** [comment]
@marla-singer and @frenchbread authenticated and anonymous users should be able to see public APIs. It may be that this is already working. Make sure that:

- all users can see public APIs
- only API manager(s) and Apinf administrators can see private APIs (`api.currentUserCanView()`)

**Comment by marla-singer** [comment]
@frenchbread Start review using remark from @brylie

**Comment by marla-singer** [comment]
@frenchbread Your work is all good.
@brylie What about permissions:
- all users can see public APIs
- only api owner can see self private api. Administrator can't see private APIs. Found bug doesn't related on this issue, so I'd like to go ahead and merge it

**Comment by brylie** [comment]
@marla-singer go ahead and merge. However, *Apinf admin users* should also be able to see private APIs, even if they are not a manager of the API.

**Comment by marla-singer** [comment]
@brylie Right now, Apinf admin users **can't see private APIs**
Screenshot:

1. User is Apinf Administrator. Catalog has 4 apis
joxi_screenshot_1475577095313

2. Log in like one of api owner. Set api as private
joxi_screenshot_1475577239491

3. Log in like Apinf administrator. Catalog has 3 apis
joxi_screenshot_1475577184490

**Comment by brylie** [comment]
OK, thanks for the screenshots. Perhaps we can move the Administrator visibility bug to another task. I will quickly check with @bajiat the scope of this task.

**Comment by brylie** [comment]
@bajiat has agreed that we can move the administrator bug to a separate issue. @marla-singer please merge.

**Pull request merged**
