### PR TITLE
Feature/add unit test

### LINKED ISSUE #1714: Write one unit test case
This task is for 2nd week of sprint 33. Get your feet wet with unit testing. 
# Resources
- Meteor Guide: [Testing](https://guide.meteor.com/testing.html)

### PR DESCRIPTION
**Pull request by mauriciovieira**
closes #1714

### CODE REVIEW

**Comment by mauriciovieira** [comment]
related https://github.com/kadirahq/flow-router/issues/608

**Comment by mauriciovieira** [comment]
and https://github.com/kadirahq/flow-router/issues/668

**Comment by marla-singer** [comment]
@mauriciovieira I studied the issue comments and as I think can fix it for us. I created the branch that is based on yours. Please test it (PR ##2455)

**Comment by mauriciovieira** [comment]
@marla-singer thank you. I am checking it out.

**Comment by mauriciovieira** [comment]
possible workaround https://github.com/kadirahq/flow-router/pull/615 (but not a solution)

**Comment by brylie** [comment]
Should we close this PR, since you are working on end-to-end testing in another PR?

**Comment by mauriciovieira** [comment]
@brylie yes.

**Pull request closed without merging**
