### PR TITLE
Include no host address when providing API Monitoring endpoint

### LINKED ISSUE #3535: Include no host address when providing API Monitoring endpoint
When API monitoring is activated, there needs to be given the endpoint to be monitored.

### Problem

At the moment whole path to endpoint, including host address must be given. It even  is not checked, whether the given URL matches with the API in question.

### Solution
**Accept only the endpoint in input field when starting monitoring**. The host address has already been given as API host, when API card is created. The given API host address and given monitoring endpoint are combined, when solving the address, to where the monitoring requests are sent.

Currently, when monitoring endpoint is given, it is expected to contain the complete path (also server address and API path). 

This is error prone and in addition to that makes it possible to set monitoring even to completely different API.

image

Giving the server address must not be possible. This should be implemented same way as when giving API base path when connecting API to proxy.

API host URL is shown, but not editable, and user gives the API base path (if not included in API host URL) and the actual endpoint.

When monitoring requests are sent, the URL is formed by combining API host url (in settings) with the input part given here.
The endpoint must also be stored in monitoring table and it must be displayed as part of monitoring data, so user can see also the endpoint, from where the response has come.

**In monitoring table there will be visible the input part given here**.

image

### PR DESCRIPTION
**Pull request by vinaytech**
Closes #3535 

## Changes
Describe your changes here as a bulleted list:
- change one
- change two

## Developer checklist
This checklist is to be completed by the PR developer:

- [ ] Alternative solutions were compared/discussed before writing code
    - [ ] trade-offs with this solution are considered acceptable
- [ ] Code in this PR adheres to the [project styleguide](CONTRIBUTING.md)
- [ ] This pull request does not decrease project test coverage
- [ ] If the code changes existing database collection(s), migration has been written
- [ ] If UI texts are added or changed, all texts are internationalized

## Reviewer checklist
Reviewed by: @matleppa 

This list is to be completed by the pull request reviewer:
- [ ] Code works as described/expected
- [ ] Code seems to be error free
    - [ ] no browser console errors visible
    - [ ] no server console errors visible
    - [ ] passes CI build
- [ ] Code is written in a way that promotes maintainability
    - [ ] easy to understand
    - [ ] well organized
    - [ ] follows project coding standards and conventions
    - [ ] well documented

### CODE REVIEW

**Comment by matleppa** [comment]
1) It seems, that the table contains more than last 24 hours of status messages.

2) @55 is going to add the layout description of the table into issue 3535. After that you can implement it.

3) Problem with input of Endpoint to monitor.

Inputting this:
image

After pressing Save button

image

It seems that extra slashes are added.

**Comment by matleppa** [comment]
General finding:
Please, use our convention, when creating new branches for changes in functionality.

feature/descriptive-name-of-branch
bugfix/descriptive-name-of-branch

**Comment by 55** [comment]
@vinaytech, check [this](https://github.com/apinf/platform/issues/3535#issuecomment-413117258).

**Comment by matleppa** [comment]
Another thing with the input of endpoint.
In example I originally gave value "vaihto".
When I pressed the Save button, the string "/cup" was added, thus "/cupvaihto".
Next press Save, again the string "/cup" was added, thus "/cup/cupvaihto".
It seem, that the logic is taking the string "/cup" from the host address part.

Fix it so, that nothing extra is added into input field.


image

**Comment by matleppa** [comment]
In case End point field is left empty and button [Save] is pressed, following errors can be seen on console:
autoform.js:29 Uncaught TypeError: Cannot read property 'replace' of undefined
    at Object.formToModifier (autoform.js:29)
    at formValuesTransform (aldeed_autoform.js?hash=62240ad3bd09e4bcabcb996180d4d6ec136db9a9:2144)
    at Array.forEach (<anonymous>)
    at Function._.each._.forEach (underscore.js?hash=cde485f60699ff9aced3305f70189e39c665183c:149)
    at Object.autoFormGetFormValues [as getFormValues] (aldeed_autoform.js?hash=62240ad3bd09e4bcabcb996180d4d6ec136db9a9:2143)
    at Object.autoFormSubmitHandler (aldeed_autoform.js?hash=62240ad3bd09e4bcabcb996180d4d6ec136db9a9:7678)
    at blaze.js?hash=f33d3dfed63a491d24e3aa07ad66c24b5fe8c761:3775
    at Function.Template._withTemplateInstanceFunc (blaze.js?hash=f33d3dfed63a491d24e3aa07ad66c24b5fe8c761:3744)
    at Blaze.View.<anonymous> (blaze.js?hash=f33d3dfed63a491d24e3aa07ad66c24b5fe8c761:3774)
    at blaze.js?hash=f33d3dfed63a491d24e3aa07ad66c24b5fe8c761:2617
    at Object.Blaze._withCurrentView (blaze.js?hash=f33d3dfed63a491d24e3aa07ad66c24b5fe8c761:2271)
    at Blaze._DOMRange.<anonymous> (blaze.js?hash=f33d3dfed63a491d24e3aa07ad66c24b5fe8c761:2616)
    at HTMLFormElement.<anonymous> (blaze.js?hash=f33d3dfed63a491d24e3aa07ad66c24b5fe8c761:863)
    at HTMLDivElement.dispatch (modules.js?hash=d662a7c21a3c4876d907641fa7765ea099199159:13814)
    at HTMLDivElement.elemData.handle (modules.js?hash=d662a7c21a3c4876d907641fa7765ea099199159:13626)
formToModifier @ autoform.js:29
formValuesTransform @ aldeed_autoform.js?hash=62240ad3bd09e4bcabcb996180d4d6ec136db9a9:2144
_.each._.forEach @ underscore.js?hash=cde485f60699ff9aced3305f70189e39c665183c:149
autoFormGetFormValues @ aldeed_autoform.js?hash=62240ad3bd09e4bcabcb996180d4d6ec136db9a9:2143
autoFormSubmitHandler @ aldeed_autoform.js?hash=62240ad3bd09e4bcabcb996180d4d6ec136db9a9:7678
(anonymous) @ blaze.js?hash=f33d3dfed63a491d24e3aa07ad66c24b5fe8c761:3775
Template._withTemplateInstanceFunc @ blaze.js?hash=f33d3dfed63a491d24e3aa07ad66c24b5fe8c761:3744
(anonymous) @ blaze.js?hash=f33d3dfed63a491d24e3aa07ad66c24b5fe8c761:3774
(anonymous) @ blaze.js?hash=f33d3dfed63a491d24e3aa07ad66c24b5fe8c761:2617
Blaze._withCurrentView @ blaze.js?hash=f33d3dfed63a491d24e3aa07ad66c24b5fe8c761:2271
(anonymous) @ blaze.js?hash=f33d3dfed63a491d24e3aa07ad66c24b5fe8c761:2616
(anonymous) @ blaze.js?hash=f33d3dfed63a491d24e3aa07ad66c24b5fe8c761:863
dispatch @ modules.js?hash=d662a7c21a3c4876d907641fa7765ea099199159:13814
elemData.handle @ modules.js?hash=d662a7c21a3c4876d907641fa7765ea099199159:13626

**Comment by ilarimikkonen** [comment]
need to check the visibility: visible always for owner + admin, but how about other users?

**Pull request merged**
