### PR TITLE
Meteor 1.8

### PR DESCRIPTION
**Pull request by brylie**
Work in progress.

### CODE REVIEW

**Comment by brylie** [comment]
OK, I worked through the errors that prevented Apinf from starting.

Now, there are browser error(s) to troubleshoot.

cc: @matleppa @ilarimikkonen

**Comment by brylie** [comment]
OK, I removed the deprecated package and a line of code, and now Apinf is running without any errors:

screenshot from 2019-01-29 20-31-55

**Comment by brylie** [comment]
@matleppa and @ilarimikkonen please test this branch.

**Comment by matleppa** [comment]
1. Cloned a new repository for platform.
2. fetched Meteor update branch.

Got warnings of some missing packages, same thing which usually happens when cloning a new repository for develop. 
After installation the upgraded version seemed to be working; data could be created successfully.

**Comment by matleppa** [comment]
### Check 2 ###
1. Cloned a new repository for platform
2. Created data
3. Fetched Meteor update branch


#### Dsplays following error ####
Your development database is using mmapv1, the old, pre-MongoDB 3.0 database engine. You should consider
upgrading to Wired Tiger, the new engine. The easiest way to do so in development is to run
meteor reset. If you'd like to migrate your database, please consult
https://docs.mongodb.org/v3.0/release-notes/3.0-upgrade/
Unexpected mongo exit code 62. Restarting.

Similar error:
 https://forums.meteor.com/t/updating-to-1-7-1-unexpected-mongo-exit-code-62-restarting/43958


Proposition for solution
orloff   Jun '18
I’m solved this with next steps:
1.Mongodump
2. Meteor reset
3. Mongorestore

**Comment by brylie** [comment]
@matleppa try cloning the repo into a fresh directory, running `meteor npm install`, and then running `meteor` on the fresh project.

**Comment by matleppa** [comment]
@brylie Yes, in a fresh directory the upgrade branch was working (check 1, although not used the meteor npm install).


Problem occurs when there already exists data. (check 2).
I guess the mongodump and mongorestore are not included in MongoDB package installed in platform?

**Comment by brylie** [comment]
Yay!

**Comment by ilarimikkonen** [comment]
Thanks Brylie!

**Pull request merged**
