### PR TITLE
Feature/delete account fix

### LINKED ISSUE #1477: 'Delete' account not responding
Steps:  

1.Visit https://nightly2.apinf.io  
2.Create account by clicking on 'Sign up'   
3.Navigate to 'Account' section    
4.Click on 'Delete Account'    
5.Click on 'Delete' button in user confirmation dialog box   

Findings: 
- Clicking on 'Delete' button doesn't respond. It  allows to close user confirmation dialog. 
- It doesn't display successful dialog    
- Logs out but still shows 'Account' view
  
Expected Result: Delete account should be complete and must display successful dialog.    

Browser:   

1. Mozilla Firefox 48.0 
(Mozilla Firefox for Ubuntu Canonical – 1.0 )   
2. Google Chrome 52.0.2743.116

Operating System:  
1. Ubuntu 16.0 LTS

Screenshot:  

selection_010  

selection_009

### LINKED ISSUE #1598: Fix navigation menu 'home' link when no logo is availale
The navigation menu contains a title text that should link to the home page. The link does not work. Fix the href, so that clicking the site title takes the user to the home page.

### PR DESCRIPTION
**Pull request by brylie**
Closes #1477 
Closes #1598 

# Changes
- redirect user to home page when deleting account
- fix navigation menu title link to home page

### CODE REVIEW

**Comment by brylie** [comment]
@apinf/developers please review.

Ping @bajiat

**Comment by bajiat** [comment]
@marla-singer Could you review this?

**Comment by marla-singer** [comment]
@bajiat Yes. I'm going to review it after lunch

**Comment by marla-singer** [comment]
@brylie Please add sAlert to display successful dialog after deleting account and I'll merge it

**Comment by brylie** [comment]
@marla-singer done. Please review.

**Comment by marla-singer** [comment]
@brylie Looks good. Merge it

**Pull request merged**
