### PR TITLE
Pagination in APIs block

### LINKED ISSUE #2341: Pagination to APIs block on the Organization page
Add or improve pagination of the API block to the Organization page. Check if the pagination from the API catalog page (grid) could be reused.

### PR DESCRIPTION
**Pull request by marla-singer**
Closes #2341

### CODE REVIEW

**Comment by brylie** [comment]
This branch is showing the "The organization doesn't have any connected APIs." message even though the local organization does have APIs attached.

# feature/pagiantion branch
screenshot_20170330_115711


# develop branch
screenshot_20170330_115931

**Comment by marla-singer** [comment]
@brylie Yeah, I know it.

**Comment by marla-singer** [comment]
@brylie I suggest removing this card "This organization doesn't have any APIs" because when the subscription is not ready, `apisCount` return `undefined` and there is this card. But after all the subscription is ready and this card is changed to APIs. 😖

**Comment by marla-singer** [comment]
I have a lot of troubles with this card!

**Comment by marla-singer** [comment]
@brylie Ready for review

**Comment by bajiat** [comment]
@mauricio Could you please review this PR?

**Comment by mauricio** [comment]
@bajiat probably got the wrong mauricio :)

**Comment by bajiat** [comment]
@mauricio Sorry for tagging you! (And thanks for replying)

@mauriciovieira Could you please review this PR?

**Comment by mauriciovieira** [comment]
Also, this is fine for dummy user.

screen shot 2017-04-05 at 17 21 13

But 

screen shot 2017-04-05 at 17 23 09

Should dummy user know that there are 2 apis instead of just one? Do we want to allow the 'dummy' users to deduce how many private APIs are registered, or we want to hide this information from them?

**Comment by marla-singer** [comment]
@mauriciovieira You should test pagination feature in Organization profile.
1. Create an organization as administrator
2. Connect APIs to this organization 
Screenshot:
joxi_screenshot_1491462673704

**Comment by marla-singer** [comment]
@bajiat Should dummy user know that there are 2 apis instead of just one? Do we want to allow the 'dummy' users to deduce how many private APIs are registered, or we want to hide this information from them?
screen shot 2017-04-05 at 17 21 13

screen shot 2017-04-05 at 17 23 09

**Comment by brylie** [comment]
The count of APIs should correspond with the number that are visible/accessible to the user, based on permissions. On a basic level, this follows the principle of *consistency*, meaning the count and number of cards should be consistent

**Comment by marla-singer** [comment]
@brylie Ok.

**Comment by marla-singer** [comment]
@brylie @mauriciovieira I created the separate issue about number of APIs on the fronted page

**Pull request merged**
