### PR TITLE
Exception tracking

### LINKED ISSUE #1986: Capture and track application exceptions
As developer I want get catch and logs exceptions from runtime. 

- Will be good have dashboard with bugs.
- Integration with GitHub issues.
- Capture runtime environment like Browser version, OS platform, etc...

My personal preference https://airbrake.io, but any tool will be good.

# To do's
* Look into open source alternatives for capturing exceptions
* Make a documented proposal with pros and cons
* Store the research and proposal in docs repository

# Definition of done (to be created by assignee)

### PR DESCRIPTION
**Pull request by marla-singer**
Closes #1986 

### How to test
- Create account in sentry.io
- run meteor with the environment variable "SENTRY_DSN"
- Throw error from browser console
- Check the sentry Dashboard

Command:
```
SENTRY_DSN="URL" meteor
```

I used to post from Meteor forum to settings Sentry
https://forums.meteor.com/t/sentry-raven-with-meteor-on-server/32383

### Changes
- Settings Client side to capture exceptions using library `raven-js`
- Settings Server side to capture exceptions using library `raven`
- Take value of Sentry DSN from Environment variable
- Update example in docker file

### CODE REVIEW

**Comment by marla-singer** [comment]
@mauriciovieira Can you review this PR?

**Comment by mauriciovieira** [comment]
@marla-singer I am investigating the error :-)

**Comment by mauriciovieira** [comment]
This [meteor not found error](https://travis-ci.org/apinf/platform/builds/247538640#L1907) on travis is pretty strange. I suspect that travis had some glitch. 

Restarting build...

**Comment by mauriciovieira** [comment]
Sorry, I am still unable to point the source of error. Locally it weirdly fails on the `01 sign up` test:

```
  01 sign up
    render
      1) should show username field


  9 passing (22s)
  1 failing

  1) 01 sign up render should show username field:
     Uncaught AssertionError: expected false to be true
      at doAsserterAsyncAndAddThen (node_modules/chai-as-promised/lib/chai-as-promised.js:293:29)
      at null.<anonymous> (node_modules/chai-as-promised/lib/chai-as-promised.js:283:21)
      at null.Object.defineProperty.get (node_modules/chai/lib/chai/utils/overwriteProperty.js:50:37)
      at Context.<anonymous> (tests/end-to-end/ui/01-sign-up.js:20:7)
      at node_modules/chimp/dist/lib/utils/fiberize.js:29:22
```

Steps:
1. `git fetch`
1. `git checkout feature/expection-tracking`
1. `nvm install v4.8.3`
1. `nvm use`
1. `yarn`
1. `meteor reset && yarn test`

It does not make sense why travis is not finding meteor on `yarn test`. But if this happens with other pull requests, in my opinion, we should stop running the tests until we solve the error.

**Comment by marla-singer** [comment]
@mauriciovieira On local side tests were passed successfully.
We're investigating with @shaliko the problem and fixed it. The problems were:

1. Test wasn't passed when `meteor` was cached. We added parameter `export PATH="$HOME/.meteor:$PATH"`
2. After that `yarn` didn't intasll npm packages and it was fault "eslint: not found". We added directly command `yarn` into `install` part
3. We changed the command for cache yarn. That was taken from [official site.](https://blog.travis-ci.com/2016-11-21-travis-ci-now-supports-yarn)

**Comment by mauriciovieira** [comment]
And the build ran in 7 minutes instead of 10 or 12 :-). Good job.

**Pull request merged**
