### PR TITLE
Feature/move api editor button behind development feature flag

### LINKED ISSUE #3404: Move API editor button behind development feature flag

### PR DESCRIPTION
**Pull request by deligence-dharmendra**
Closes #3404

## Changes

- changes in view.html and view.js file
- add new method development features and changes in subscription

## Developer checklist
This checklist is to be completed by the PR developer:

- [ ] Alternative solutions were compared/discussed before writing code
    - [ ] trade-offs with this solution are considered acceptable
- [ ] Code in this PR adheres to the [project styleguide](CONTRIBUTING.md)
- [ ] This pull request does not decrease project test coverage
- [ ] If the code changes existing database collection(s), migration has been written
- [ ] If UI texts are added or changed, all texts are internationalized

## Reviewer checklist
Reviewed by: @marla-singer @matleppa 

This list is to be completed by the pull request reviewer:
- [ ] Code works as described/expected
- [ ] Code seems to be error free
    - [ ] no browser console errors visible
    - [ ] no server console errors visible
    - [ ] passes CI build
- [ ] Code is written in a way that promotes maintainability
    - [ ] easy to understand
    - [ ] well organized
    - [ ] follows project coding standards and conventions
    - [ ] well documented

### CODE REVIEW

**Comment by Nazarah** [comment]
@deligence-dharmendra tried to run your branch in my localhost.
but from Settings, on checking Enable Development Feature, I didn't see any option enable/disable Open Editor button.

**Comment by deligence-dharmendra** [comment]
@Nazarah There is no option available for enable/disable editor button, it is by hardcode flag. all features available under development features flag will automatically disappear if development features enabled in the Settings section. Please see the attached snapshot.

1) Development Features enable
settings enable
aa ml api catalog

1) Development Features disable
settings disable
aa ml api catalog_disable

**Comment by Nazarah** [comment]
@deligence-dharmendra It seems you accidentally implemented the opposite logic. :)
"Enable development feature" flag controls the visibility of the "Open editor" button which is at the Documentation tab in an API profile.
The logic is:
if (Enable development feature= CHECKED,) **show** "Open editor" button.
if (Enable development feature= UNCHECKED,) **hide** "Open editor" button.

I have confirmed it with @matleppa and @preriasusi

**Comment by marla-singer** [comment]
@deligence-dharmendra Squash all your commits and let's merge it

**Pull request merged**
