### PR TITLE
Cases for local & github registration

### LINKED ISSUE #1856: Github user's email is verified by default, no need to send verification email
```
I20161102-10:42:10.320(2)? Exception in setTimeout callback: Error: That user has no unverified email addresses.
I20161102-10:42:10.320(2)?     at AccountsServer.Accounts.sendVerificationEmail (packages/accounts-password/password_server.js:756:13)
I20161102-10:42:10.321(2)?     at [object Object].sendRegistrationEmailVerification (users/server/methods.js:34:16)
I20161102-10:42:10.321(2)?     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1711:12)
I20161102-10:42:10.322(2)?     at packages/ddp-server/livedata_server.js:1624:18
I20161102-10:42:10.322(2)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20161102-10:42:10.323(2)?     at Server.apply (packages/ddp-server/livedata_server.js:1623:45)
I20161102-10:42:10.323(2)?     at Server.call (packages/ddp-server/livedata_server.js:1566:17)
I20161102-10:42:10.323(2)?     at users/server/accounts_hooks.js:32:12
I20161102-10:42:10.324(2)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20161102-10:42:10.324(2)?     at packages/meteor/timers.js:6:1
```

### PR DESCRIPTION
**Pull request by jykae**
Closes #1856 

- add blocks for local & github registration, no need to send verification email on Github registration

### CODE REVIEW

**Comment by marla-singer** [comment]
@jykae Case 1 doesn't work as expected. 
**Steps**

1. Create user with name _testapinf123_
2. Log out
3. Sign up via GitHub using credentials: 
 - testapinf123 
 - q1w2e3r4

Found result: 
- Redirecte to profile page
- 404 error
joxi_screenshot_1478161060047

**Comment by marla-singer** [comment]
As recomendation it should show some popup after redirect with a message "Enter your username" or something like this. These isn't obviously why it redirects to profile, why my user name doesn't appear in right up corner? 
User can be confused
joxi_screenshot_1478161475897

**Comment by jykae** [comment]
@marla-singer Redirect issue fixed in PR #1865 as continuance for this.

**Comment by marla-singer** [comment]
@jykae I'm testing this case on another PR

**Comment by jykae** [comment]
```
3. Sign up via GitHub using credentials: 
 - testapinf123 
 - q1w2e3r4
```
Those are not probably your Github account credentials, so this is testing what happens when Github registration/login fails? I check out the case. thanks for testing, @marla-singer

**Comment by marla-singer** [comment]
@jykae Nope. Ilia created this credentials special for test (when he fixed registration test)

**Comment by jykae** [comment]
Ah, so this user exists, https://github.com/testapinf123 :D sadly has not contributed a lot :/

**Comment by marla-singer** [comment]
@jykae He has the world before one ;)

**Comment by jykae** [comment]
@marla-singer I think you had username "testapinf123" already in use for what you found. I get logged in nicely with "testapinf123". Does this need any further steps or can be merged?

**Comment by marla-singer** [comment]
@jykae I think this branch we can merge. Issue with username is being resolved on another branch.

**Pull request merged**
