### PR TITLE
Add checks for unique & regex validation errors

### PR DESCRIPTION
**Pull request by jykae**
Tested against staging DB dump.

TODO:
- update proxyBackends to Umbrella

### CODE REVIEW

**Comment by bajiat** [comment]
Let's handle updating proxyBackends to Umbrella in another issue

**Comment by bajiat** [comment]
@marla-singer Could you review Ville's PR?

**Comment by marla-singer** [comment]
@bajiat Yes, I'm starting after lunch

**Comment by bajiat** [comment]
@marla-singer Correction to previous. We are putting this on hold, keeping the branch, but not merging it now.

**Comment by marla-singer** [comment]
@bajiat Okay. I'll tested it and do code review after I won't merge

**Comment by jykae** [comment]
@marla-singer Decision here was to keep branch, just close PR.

**Comment by marla-singer** [comment]
@jykae How did you test migration? Maybe I did something wrong
1. I have the 'apiBackend' collection and empty 'apis' collection
2. Start meteor project. Have in console `Migrations: Not migrating, already at version 2`
3. Then I add on startup calling ``` migrateApiBackends()```
4. Start meteor project.

I have an error `MongoError: E11000 duplicate key error collection: meteor.apis index: c2_name dup key: { : "api" }`

Then I added console.log in part 
```javascript
catch (error) {
 console.log(error); ...
}
```
I have the next error: `[ReferenceError: error is not defined]`
Is it okay?

**Comment by marla-singer** [comment]
@jykae Well, I see how to run migration

**Comment by marla-singer** [comment]
@jykae Very unstable results. I think It happens because all mongo manipulations are async. And sometimes it works as expected, but in more cases - not.
## Screenshots
Fail

Success


## Steps

Repeat the next steps several times:

1. Drop apis and proxyBackends collections
2. Set migration has version as 1 and loacked as false. 
3. Restart meteor project. 
4. Watch server console error

apiBackends collections has values:

```json
{
        "_id" : ObjectId("57fe457b2c3c752f195badc5"),
        "name" : "api",
        "backend_protocol" : "http",
        "backend_host" : "api.com",
        "managerIds" : [
                "HwssZ2CitatGdCSPa"
        ],
        "url_matches" : [
                {
                        "frontend_prefix" : "/joku/",
                        "backend_prefix" : "/"
                }
        ]
}
{
        "_id" : ObjectId("57fe458a2c3c752f195badc6"),
        "name" : "api2",
        "backend_protocol" : "http",
        "backend_host" : "api.com",
        "managerIds" : [
                "HwssZ2CitatGdCSPa"
        ],
        "url_matches" : [
                {
                        "frontend_prefix" : "/joku/",
                        "backend_prefix" : "/"
                }
        ]
}
{
        "_id" : ObjectId("57fe45972c3c752f195badc7"),
        "name" : "api3",
        "backend_protocol" : "http",
        "backend_host" : "api.com",
        "managerIds" : [
                "HwssZ2CitatGdCSPa"
        ],
        "url_matches" : [
                {
                        "frontend_prefix" : "/joku/",
                        "backend_prefix" : "/a"
                }
        ]
}
{
        "_id" : ObjectId("57fe45a12c3c752f195badc8"),
        "name" : "api3",
        "backend_protocol" : "http",
        "backend_host" : "api.com",
        "managerIds" : [
                "HwssZ2CitatGdCSPa"
        ],
        "url_matches" : [
                {
                        "frontend_prefix" : "/joku/a",
                        "backend_prefix" : "/a/"
                }
        ]
}
{
        "_id" : ObjectId("57fe4ceb2c3c752f195badc9"),
        "name" : "api3",
        "backend_protocol" : "http",
        "backend_host" : "api.com",
        "managerIds" : [
                "HwssZ2CitatGdCSPa"
        ],
        "url_matches" : [
                {
                        "frontend_prefix" : "/joku/a",
                        "backend_prefix" : "/a/"
                }
        ]
}
```

**Comment by jykae** [comment]
Thanks for review I found same sort of unstability because async nature of node.js

**Pull request closed without merging**
