### PR TITLE
Hotfix/uploading swagger

### LINKED ISSUE #1700: Incorrect work of uploading file
Step to reproduce:
1. Go to api Documentation tab. 
2. Set "GPRS" presets on Network tab in Google Dev Tools
3. Open Manage modal. Choose file

Found result: The documentation isn't uploaded yet, but Swagger tries to valid this file. 

Expected result: Swagger must check for validation documentation when it's already uploaded

### LINKED ISSUE #1701: Incorrect work of deleting file
Step to reproduce:
1. Go to Documentation tab and open Manage model.
2. Choose file and delete it . Don't click another button. Only **Choose file** and **Delete file**

Found result: Swagger body didn't remove
Screenshot:
joxi_screenshot_1475742125450

Expected result: Empty scope 
Screenshot:
joxi_screenshot_1475742151977

### PR DESCRIPTION
**Pull request by marla-singer**
Closes #1700
Closes #1701

### CODE REVIEW

**Comment by bajiat** [comment]
@marla-singer: @jykae promised to mentor and review.

**Comment by jykae** [comment]
Reviewing

**Comment by jykae** [comment]
@marla-singer #1701 seems to function right.

However with GPRS presets on I get this kind of situation, spinner spinning and resumable errors to console.
nayttokuva 2016-10-06 kello 16 01 01

**Comment by marla-singer** [comment]
@jykae Please do screenshot Network tab then you upload file

**Comment by marla-singer** [comment]
@jykae Which OS and browser do you use?

**Comment by jykae** [comment]
View with network tab open:
nayttokuva 2016-10-06 kello 16 34 45

**Comment by marla-singer** [comment]
Well, GPRS presets looks bad for testing feature. File's uploaded too slow. Time is out and connection closes :-1: 
please test it on "Regular 2G" presets. File will be uploaded ~2min

**Comment by jykae** [comment]
@marla-singer macOS Sierra is quite new, maybe it's related to Chrome on Sierra, error comes from resumable.js code. Check versions above in previous screenshot.
Maybe someone else could check with Chrome/Chromium, that is not on macOS Sierra.

EDIT: ok, I try out with "Regular 2G".

**Comment by jykae** [comment]
"Regular 2G" works as expected 👍

**Comment by marla-singer** [comment]
@jykae Aha, I think so. When I tested it on Hackintosh with macOS Sierra, i had this problem too. Connection open only ~6 sec. But I slandered the pirate OS :D

**Comment by jykae** [comment]
@marla-singer I think we can merge this, if there's still issue let's open new one.

**Pull request merged**
