### PR TITLE
Fix collections security

### PR DESCRIPTION
**Pull request by manzapanza**
Closes: #1417

### CODE REVIEW

**Comment by manzapanza** [comment]
@matleppa Unfortunately I wasn't able to test ApiKey permissions because the add proxy throw an error (as reported #2381 Adding Proxy settings fails in staging)

**Comment by marla-singer** [comment]
@manzapanza Please update `develop` branch it should be resolved by PR #2596

**Comment by matleppa** [comment]
@manzapanza Any progress after advice from @marla-singer ?

**Comment by bajiat** [comment]
Closing this since the branch is outdated and there is no progress.

**Pull request closed without merging**
