### PR TITLE
Added field descriptions and placeholders in Add API fields

### LINKED ISSUE #3403: Add api feature: Add descriptions to all fields
- short description texts can be shown as disabled text within a field itself
- long description can be added as a tooltip with info icon.

### PR DESCRIPTION
**Pull request by Nazarah**
Closes #3403

## Changes
1. **i18n.json:** added templates `addApi_nameFieldInfo`, `addApi_descriptionFieldInfo` and `addApi_urlFieldInfo` which describe purpose of name, description and URL fields (respectively) in Add API page.

2. **i18n.json**: added template `addApi_ownerHelpText` that describes where an added API appears with what visibility.

3. **schema.json**: added placeholder values under autoform attribute for Name, Description and URL fields.

4. **add.html**: added templates texts describing the purpose of **name**, **description** and **url** fields.

5. **add.html**: added template text describing where added API appears with what visibility.

6. **add.less**: added new css class `field-description-text` to style field description texts.

## Developer checklist
This checklist is to be completed by the PR developer:

- [ ] Alternative solutions were compared/discussed before writing code
    - [ ] trade-offs with this solution are considered acceptable
- [ ] Code in this PR adheres to the [project styleguide](CONTRIBUTING.md)
- [ ] This pull request does not decrease project test coverage
- [ ] If the code changes existing database collection(s), migration has been written
- [ ] If UI texts are added or changed, all texts are internationalized

## Reviewer checklist
Reviewed by: @username1

This list is to be completed by the pull request reviewer:
- [ ] Code works as described/expected
- [ ] Code seems to be error free
    - [ ] no browser console errors visible
    - [ ] no server console errors visible
    - [ ] passes CI build
- [ ] Code is written in a way that promotes maintainability
    - [ ] easy to understand
    - [ ] well organized
    - [ ] follows project coding standards and conventions
    - [ ] well documented

### CODE REVIEW

**Comment by matleppa** [comment]
I'd suggest the description texts to be moved above the input field in order to keep them visible also in case the browser generates and adds a drop-down menu into input field.
An example added into issue 3403.

**Comment by 55** [comment]
@matleppa let's not do it. Ecstatically it looks better as it's now. Help text != description (which has to go after title).

**Comment by Nazarah** [comment]
@matleppa before adding the templates to show help texts, the code used to be like the following:


```
{{# autoForm collection=ApisCollection id="addApiForm" type="insert" }}
          <!--invisible auto-value field-->
          {{> afQuickField name='latestMonitoringStatusCode' value="-1" type="hidden"}}
          <fieldset>
            {{> afQuickField name='name' id="api-name" }}
            {{> afQuickField name='description' rows=2 id="api-description" }}
            {{> afQuickField name='url' id="api-url" }}
            {{> afQuickField name='lifecycleStatus' id="api-lifecyclestatus" }}
          </fieldset>
          <button type="submit" class="btn btn-primary" id="submitapi-button">
            {{_ 'addApi_button_text' }}
          </button>
        {{/ autoForm }}
```

It means the fields are being populated using the Autoform package.
Also each individual field is defined using `{{> afQuickField }}` helpers.
For this reason, I was unable to find a way to display the help text between the input label and input field.
As an alternative solution, I added the description text for each field below the input field with by creating a new class `.field-description-text` in add.less

**Comment by matleppa** [comment]
@55 OK, we can call it help text instead of description. 
I think that helping user has a priority over aesthetic values.

It seems that in this very case there are some challenges because of use of afQuickField.

**Pull request merged**
