### PR TITLE
Add Authorized users to API by using username

### LINKED ISSUE #3365: Ability to add Authorized users to API by using username
Currently, you can add **Authorized users** to APInf Profile with email. Would be convenient to add these users also by username.

Task make it possible to add members with username.

### PR DESCRIPTION
**Pull request by marla-singer**
Closes #3365

## Developer checklist
This checklist is to be completed by the PR developer:

- [ ] Alternative solutions were compared/discussed before writing code
    - [ ] trade-offs with this solution are considered acceptable
- [ ] Code in this PR adheres to the [project styleguide](CONTRIBUTING.md)
- [ ] This pull request does not decrease project test coverage
- [ ] If the code changes existing database collection(s), migration has been written
- [ ] If UI texts are added or changed, all texts are internationalized

## Reviewer checklist
Reviewed by: @username1

This list is to be completed by the pull request reviewer:
- [ ] Code works as described/expected
- [ ] Code seems to be error free
    - [ ] no browser console errors visible
    - [ ] no server console errors visible
    - [ ] passes CI build
- [ ] Code is written in a way that promotes maintainability
    - [ ] easy to understand
    - [ ] well organized
    - [ ] follows project coding standards and conventions
    - [ ] well documented

### CODE REVIEW

**Comment by marla-singer** [comment]
> Correction to title:
Add authorized users --> Add new authorized user

Don't agree, "new" is redundant

> Between title and input field a guidance text:
"Give either username or email address"

Will do it

**Comment by matleppa** [comment]
OK.

Add authorized users
-->
Add authorized user

Because users are added one at a time.

**Comment by marla-singer** [comment]
@matleppa Actual, the original text is in single number

**Comment by matleppa** [comment]
The title, yes. Now it seems to be fine.

**Pull request merged**
