### PR TITLE
Feature/branding color ui

### LINKED ISSUE #1793: Allow users to change branding color
Allow system admins to change main branding color from branding settings.

>  As an Apinf customer, I want to change the bright blue color to my company's or organization's brand color
so that Apinf deployment is in line with our other web pages and it matches with our logo color(s).

# Definition of done
* [ ] User can change the branding color in branding settings.
* [ ] User can use a color picker to either type the color value (RGB or HEX)
* [ ] The setting affects
  * [ ] nav bar
  * [ ] cover photo
  * [ ] search box
  * [ ] language option active, if possible
  * [ ] settings menu list group item active, if possible
  * [ ] API navigation tab active, if possible
  * [ ] intro.js bullet active, if possible
  * [ ] catalog active pagination, if possible
* [ ] User can also change the font color for text (links) in navbar

### PR DESCRIPTION
**Pull request by brylie**
Closes #1793 

# Changes
- Add colors field to schema
  -  add primary sub-field
  - add primary text sub field
- Add colors field to Branding page
- Add color picker (Bootstrap Colorpicker) to color fields
- Add customStylesheet template
- Include customStylesheet template in main layout body
- Change 'About' button markup to use anchor, rather than button
- Add selectors for all elements that should have primary color and text color
- Add method to change active navbar menu background item based on lightening or darkening for best contrast

### CODE REVIEW

**Comment by jykae** [comment]
@brylie reviewing

**Comment by jykae** [comment]
@brylie Discussed with @bajiat , would active color of settings menu item change also?

nayttokuva 2016-10-27 kello 9 50 58

**Comment by brylie** [comment]
@bajiat thoughts?

**Comment by brylie** [comment]
@jykae done.

screenshot_20161027_102939

**Comment by jykae** [comment]
@brylie Search box corners in navigation:
nayttokuva 2016-10-27 kello 10 45 32

**Comment by brylie** [comment]
@jykae done.

screenshot_20161027_112547

**Comment by jykae** [comment]
@brylie great work, merging

**Pull request merged**
