### PR TITLE
Use bootstrap-datepicker for metadata Dates

### LINKED ISSUE #852: Service validation period not shown in 'Metadata' view
# Steps
1. Visit https://nightly.apinf.io 
2. Login
3. Add API Backend
4. Go to Manage API Backends
5. Click on 'View' button
6. Go to Metadata and click on 'Edit API Metadata'
7. Enter the following details:
   -  Organization: Name and Description
   -  Contact: Email id and phone number
   -  Service: Name, Description, Validation period and Service level Agreement
8. Click on 'Submit' button
# Findings

 'Service validation period' not shown  in 'Metadata' view

### LINKED ISSUE #853: Input data handling error for service validation period
# Steps
1. Visit https://nightly.apinf.io 
2. Login
3. Add API Backend
4. Go to Manage API Backends
5. Click on 'View' button
6. Go to Metadata and click on 'Edit API Metadata'
7. Enter the following details:
   -  Organization: Name and Description
   -  Contact: Email id and phone number
   -  Service: Name, Description
8. Enter invalid  data for validation period (eg: abc...xyz, 11111....22222)
9. Enter service level agreement
10. Click on 'Submit' button
# Findings
-  User not notified to validate the input data for validation period
-  'Service validation period'  not shown in 'Metadata' view

### LINKED ISSUE #854: Calendar view missing for service validation period fields
# Steps
1. Visit https://nightly.apinf.io 
2. Login
3. Add API Backend
4. Go to Manage API Backends
5. Click on 'View' button
6. Go to Metadata and click on 'Edit API Metadata'
7. Enter the following details:
   -  Organization: Name and Description
   -  Contact: Email id and phone number
   -  Service: Name, Description,Validation period 
# Findings

Calendar view missing for validation period fields  
# Screenshots

Internet Explorer 11 and Mozilla Firefox 44.0 

metadata_service_validation_ie

Google Chrome

calender_view_chrome_firefox_edge

 Google Chrome 
calender_view_chrome

Microsoft Edge 25.10586.0.0  

calender_view_ms_edge

### PR DESCRIPTION
**Pull request by jykae**
Closes #852 
Closes #853 
Closes #854

### CODE REVIEW

**Comment by marla-singer** [comment]
@jykae Yeah, works good and error handler has too. If this type of date is acceptable, I will merge it
joxi_screenshot_1478700179991

**Comment by jykae** [comment]
@marla-singer I check tomorrow if I could possibly make it nicer. At least remove time part away.

**Comment by jykae** [comment]
@marla-singer date format improved

**Comment by marla-singer** [comment]
@jykae Validate date isn't updated if I change only one date.
Steps: Enter both field: Validate since and Validate until, save it
Click on button "Edit metadata"  and delete one of these fields, save it
Found: Fields aren't updated

But if you delete both fields, they'll disappear both

**Comment by jykae** [comment]
Good find, there is an open issue, https://github.com/aldeed/meteor-autoform-bs-datepicker/issues/24

 I try to figure out something..

**Comment by marla-singer** [comment]
@jykae I will approve it on Monday

**Comment by jykae** [comment]
Forked, fixed, published package with fix. https://github.com/apinf/meteor-autoform-bs-datepicker

**Comment by jykae** [comment]
@marla-singer how it feels now? does it function like it expected?

**Comment by marla-singer** [comment]
@jykae Unfortunatly no :( Now If Validate since and Validate util exist and I try to delete only Validate until then I have message about "End date must be after begin date"

**Comment by jykae** [comment]
@marla-singer how you would like it to behave? Only validate time frame if BOTH fields have value? And allow cases: only valid since value & only valid until value?

**Comment by marla-singer** [comment]
@jykae Steps:
1. Fill the fields "Valid since" and "Valid until" with the correct date
2. Save forn
3. Click on button "Edit metadata" and delete the value from "Valid until"
4. Click on Save button

I've got the next results

**Comment by jykae** [comment]
@marla-singer added check, now we compare only if we have both Dates. How about now?

**Comment by marla-singer** [comment]
@jykae Good. Merge it

**Pull request merged**
