### PR TITLE
Feature/use yarn on travis

### LINKED ISSUE #2476: Experiment with using yarn instead of npm
# Description
Try using yarn commands instead of nmp in development. Document any problems.

Experiment will take place during 2nd wk of sprint 41

### PR DESCRIPTION
**Pull request by mauriciovieira**
closes #2476

### CODE REVIEW

**Comment by phanimahesh** [comment]
All good, but yarn looks outdated. Can you add the following to travis.yml?
```
cache:
  yarn: true
addons:
  apt:
    sources:
      - sourceline: 'deb https://dl.yarnpkg.com/debian/ stable main'
        key_url: 'https://dl.yarnpkg.com/debian/pubkey.gpg'
    packages:
      - yarn
```

**Comment by mauriciovieira** [comment]
@phanimahesh I was about to commit [yarn's website instructions](https://yarnpkg.com/en/docs/install-ci#travis-tab):

> sudo: required
> before_install: # if "install" is overridden
>   # Repo for Yarn
>   - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
>   - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
>   - sudo apt-get update -qq
>   - sudo apt-get install -y -qq yarn=0.23.2
> cache:
>   yarn: true

Do you think it's better to lock version on 0.23.2 or no?

**Comment by mauriciovieira** [comment]
OK!

**Comment by phanimahesh** [comment]
We shouldn't lock the yarn version, and your suggestion requires enabling sudo which is unnecessary since yarn repos are on apt whitelist of travis, and enabling sudo means our builds won't run in containers which _may_ slow build times slightly.

**Comment by mauriciovieira** [comment]
@phanimahesh https://travis-ci.org/apinf/platform/builds/224373898#L294 yarn 0.17.8 :-/

**Comment by mauriciovieira** [comment]
@phanimahesh https://travis-ci.org/apinf/platform/builds/224385220#L341 0.23.2 :handshake:

**Comment by phanimahesh** [comment]
Let's just go with script install as suggested in yarn docs, then.

**Comment by mauriciovieira** [comment]
@phanimahesh you mean https://github.com/apinf/platform/pull/2485/commits/12fcf813198dba4295077250995f65d3c02e6d4b ?

**Comment by phanimahesh** [comment]
Merged in https://github.com/apinf/platform/commit/bdb13c8fde6f2605b155b75447fec821406e45a9. My comment was delayed, it was addressed in 12fcf81, yes.

**Pull request merged**
