### PR TITLE
update yarn.lock

### PR DESCRIPTION
**Pull request by phanimahesh**

### CODE REVIEW

**Comment by bajiat** [comment]
@marla-singer Are you using yarn? Could you review this PR?

**Comment by marla-singer** [comment]
@bajiat Sure
@phanimahesh Please look at Travic-CI log, your changes have error. Also set the label "Ready for review" or ping me when it will be ready

**Comment by bajiat** [comment]
@marla-singer and @phanimahesh Should this PR be merged, closed or updated to correct the errors in Travis CI log?

**Comment by marla-singer** [comment]
@bajiat 
> updated to correct the errors in Travis CI log

**Comment by bajiat** [comment]
@marla-singer Is this PR valid any more? Does it make any sense to update it or should we open a new one to update?

**Comment by phanimahesh** [comment]
Let's close this one, there have been a lot of updates meanwhile

**Comment by bajiat** [comment]
Closing as per suggestion.

**Pull request closed without merging**
