### PR TITLE
Fix rate limiting settings

### LINKED ISSUE #1190: Add and test rate limiting field to Proxy backend collection
(Description updated due to multiproxy development) Rate limiting setting is one of the key settings API owner needs in order to control the traffic to the API. Make sure it works correctly in Apinf - to the extent that API Umbrella supports it. Add the field to the new Proxy Backends collection

# Potential user stories
> 
 As an API owner 
I want to limit the usage of my API for a 
particular API consumer
 
> As an API owner
I want to be able to set and change a default rate limit 
for my API for a certain period of time

# Definition of done
* [x] Make sure the rate limiting options get stored in the Proxy Backends collection
* [x] Make sure the options are aligned with Api Umbrella
* [x] Make sure the selected option is passed correctly to the Admin REST API
  * [ ] Optional idea: start by testing passing the setting with a REST call only (e.g. Postman)
* [x] Make sure it gets stored (and changed when updated) properly in API Umbrella
* [x] Make sure there is a setting for rate limiting in Proxy tab in API profile

# Wireframe

Scenario 1: API owner sets default request rate of API-Umbrella Proxy

apiratelimit

Scenario 2: API Owner customizes Request Rate Limits based on API key or specific IP Address. There can be multiple customizations and may vary by durations (seconds/minutes/hours etc.). Owner can select a customized settings as primary.

apiratelimit2

apiratelimit3

apiratelimit4

Scenario 3: API owner sets unlimited API calls

apiratelimit5

### PR DESCRIPTION
**Pull request by jykae**
Closes #1190 

## Proposed changes
- fix rate limiting fields based on Umbrella Admin API

### CODE REVIEW

**Comment by nnn** [comment]
@frenchbread, could you please review this PR?

**Comment by frenchbread** [comment]
@jykae Have you been able to test what happens when amount of requests is over the rate limit? I've set a custom rate limit for sample API backend and it doesn't seem to work. What's the workflow for testing, if i'm doing it wrong?

**Comment by jykae** [comment]
@frenchbread I tested this with shell script oneliner that had for loop that runs several requests.
```
for ((i=1;i<=1000;i++)); do curl -I https://nightly.umbrella.apinf.io/teosto/event; done
```
That's probably the simplest way. I would like to know the fields in Apinf edit form that you have set, if they were understood right?

I commented in the main issue about rate limiting when I first tested just with Umbrella Admin UI.

When rate limits hits boundaries, Umbrella gives HTTP status 429:
```
HTTP/1.1 429
Server: openresty
Date: Thu, 28 Jul 2016 08:14:53 GMT
Content-Type: application/json
Connection: keep-alive
X-RateLimit-Limit: 1000
X-RateLimit-Remaining: 0
Access-Control-Allow-Origin: *
X-Cache: MISS
Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
```
Interesting headers here are HTTP status 429 and X-RateLimit headers.

**Comment by brylie** [comment]
Please resolve conflicts.

**Comment by brylie** [comment]
When testing the rate limit settings, I get the following errors when submitting:

```js
failed [422] {"errors":{"settings.rate_limits[0].duration":["can't be blank","is not a number"],"settings.rate_limits[0].accuracy":["can't be blank","is not a number"],"settings.rate_limits[0].limit_by":["can't be blank","is not included in the list"],"settings.rate_limits[0].limit":["can't be blank","is not a number"]}}
```

**Comment by jykae** [comment]
@brylie Weird, haven't seen those before. I will get to this after I have visibility feature ready, and PR accepted.

**Comment by jykae** [comment]
Closing this one..

**Pull request closed without merging**
