### PR TITLE
Feature/update swagger host

### LINKED ISSUE #1360: Update host name in Swagger file automatically
A swagger file will include a host name. This should be replaced with the URL used at apinf.io
e.g. api.mycompany.com/list (original swagger file) > apinf.io/mycompany/list?key=abc (swagger-ui)

Also the key should be included if required. If user is not logged in, then show a message that in order to use the API, you need a key (and thus an account).

# Definition of done
* [ ] Before displaying the file to the user, the viewer checks whether the API is connected to a proxy. If the API is connected to a proxy, the viewer updates the following, if necessary
  * [x] Host name in the Swagger file: original base URL replaced with apinf base URL: 
e.g. api.mycompany.com/list (original swagger file) > apinf.io/mycompany/list?key=abc (swagger-ui)
  * [x] Add API key authorization and use the end user's API key.
Open issue: What if the user does not have an API key? Either the user could be an anonymous (unregistered) user or a registered user who has not pressed the Get API key button?

### PR DESCRIPTION
**Pull request by marla-singer**
Closes #1360

### Testing api Key authorization
1. Add Swagger file which is supported Authorization. For example [http://petstore.swagger.io/v2/swagger.json](http://petstore.swagger.io/v2/swagger.json)
2. Go to API details and click on button "Get API Key"
3. Go to Documentation tab and click on button "Authorization"
4. Popup will be showed as on screenshot, field "value" contains the value of api key. 
 If it doesn't happen, close popup and open again. 
joxi_screenshot_1474370327740

### CODE REVIEW

**Comment by jykae** [comment]
Reviewing

**Comment by jykae** [comment]
@marla-singer Rendering stuck

nayttokuva 2016-09-20 kello 10 47 55

**Comment by marla-singer** [comment]
@jykae Describe please your steps

**Comment by marla-singer** [comment]
@jykae Also ping me if you face this issue #1588  (it'll be great if you can describe to me when this issue is appeared because I can't catch it)

**Comment by jykae** [comment]
This is possible related to issue:
nayttokuva 2016-09-20 kello 11 24 27

Coming from Swagger UI utils:
nayttokuva 2016-09-20 kello 11 25 42

Cannot parse securityDefinitions :/ I try one simpler without those if same issue.

**Comment by marla-singer** [comment]
@jykae It could be problem with node packages version. Can you please delete the folder "node_modules", run `npm i` and try again?

**Comment by jykae** [comment]
Loaded with this: https://github.com/OAI/OpenAPI-Specification/blob/master/examples/v2.0/json/petstore-expanded.json

**Comment by marla-singer** [comment]
@jykae It's work correct on my side
joxi_screenshot_1474360997859

>@jykae It could be problem with node packages version. Can you please delete the folder "node_modules", run npm i and try again?

Please try these recomendation

**Comment by marla-singer** [comment]
@jykae I found another problem. I'll write you after fixes

**Comment by jykae** [comment]
Looks like it is basically built right.
nayttokuva 2016-09-20 kello 11 45 16

Did npm package updates.

**Comment by marla-singer** [comment]
@jykae Test please with api key too. I pushed fixes

**Comment by jykae** [comment]
@marla-singer do you have steps how to it should work with swagger?

**Comment by marla-singer** [comment]
@jykae Add steps on PR description

**Comment by jykae** [comment]
Cool, it works! :)

**Comment by jykae** [comment]
@marla-singer Also eslint your code for "swaggerUiContent.js" for example.
We have recently started to require it in PRs. In our architect @brylie 's words "Fix at least some errors." As our .eslintrc is not yet fully proper, but we are going towards better code step by step.

nayttokuva 2016-09-20 kello 17 00 16

**Comment by marla-singer** [comment]
@jykae lint. However I don't know what to do with problem like "Template is not defined", "Meteor is not defined", "Unexpected dangling '_' in '_id' "

**Comment by jykae** [comment]
@marla-singer If you are using eg. Atom you can click those errors and it opens to browser a page about error and examples how to correct.

Eg. How to fix undefined classes & variables:
```
import { Meteor } from 'meteor/meteor';
import { Template } from 'meteor/templating';
```
Clicking "no-undef" would give link: http://eslint.org/docs/rules/no-undef

There are some cases we need to allow in our rules like underscore-dangle in front of "id" that our DB objects use. If you find that kind of case that does not make sense, you can provide a fix to .eslintrc or just note reviewer so that it will eventually end up to allow if agreed so by higher orders :)

**Comment by marla-singer** [comment]
@jykae Thank for your recommendations! I finished it

**Pull request merged**
