### PR TITLE
Feature/email verification fix

### LINKED ISSUE #1836: Sign up allows user to login without completing email verification
# Steps
1. Visit https://staging.apinf.io 
2. Click on 'Sign up'  
3. Enter username  
4. Enter email 
5. Enter Password  
6. Re-enter the same password for confirmation  
7. Click on 'Register'  
# Findings
-  Click on 'Register' leads to automatic login  
-  Email verification message sent to the user  
-  Allows to logout-login without completing email verification  
# Expected Result

User not allowed to login without completing email verification   
# Browser
1. Mozilla Firefox 48.0 
   (Mozilla Firefox for Ubuntu Canonical – 1.0 )  
2. Google Chrome 52.0.2743.116
# Operating System

Ubuntu 16.0 LTS

### PR DESCRIPTION
**Pull request by brylie**
Closes #1836
# Changes
- fix login validation method
- always run login validation method
- update validateSmtpSettings method
- cleanup

### CODE REVIEW

**Comment by marla-singer** [comment]
@brylie These is resovled issue. But I have the next information in meteor console:
```
====== BEGIN MAIL #0 ======

(Mail not sent; to enable sending, set the MAIL_URL environment variable.)
```

**Comment by brylie** [comment]
Right, the mail settings have to be configured in order for the MAIL_URL environmental variable to be set.

**Comment by brylie** [comment]
We have enabled verification emails at all times, which means that Meteor will sometimes try to send emails when the `MAIL_URL` environmental variable is not set. This is intentional, for now. We have a follow up task https://github.com/apinf/platform/issues/1843

**Comment by marla-singer** [comment]
> This is intentional, for now.

So, should I merge it? When MAIL_ENV is not set, emaild doesn't send to user.

**Comment by brylie** [comment]
Jep. That is expected. We have to figure out how to dynamically enable the email related features, but in the meantime opted to enable them by default.

**Comment by marla-singer** [comment]
@brylie I'm goint to merge it with a view to MAIL_ENV will be set and will work correct in the PR for 1843 issue

**Pull request merged**
