### PR TITLE
Work in Progress on issue #3061

### LINKED ISSUE #3061: Add API using Swagger file: parse json and yaml
# User story
As an API owner, I would like to be able to upload or link a Swagger file so that I can add an API to Catalog without manually entering the same data that can already be found from my Swagger file.

# Goal
The goal of this task is to solve basic first steps for adding an API with reading data from Swagger file
* Get familiar with OpenAPI 2.0 specification and understand which fields in the Swagger document can be mapped to these APInf fields
  * Name
  * URL
  * Description
  * lifecycle status
* Find suitable open source NPM packages for
  * parsing YAML
  * parsing JSON
* Figure out how to validate, whether the file is valid Swagger file, valid json, valid yaml

Note: the actual UI implementation of Add API using Swagger to follow later.

### PR DESCRIPTION
**Pull request by saransh-dev**
Closes #3061 

## Changes
- and a modal to upload file or like for adding api.

## Developer checklist
This checklist is to be completed by the PR developer:

- [x] Alternative solutions were compared/discussed before writing code
    - [ ] trade-offs with this solution are considered acceptable
- [x] Code in this PR adheres to the [project styleguide](CONTRIBUTING.md)
- [x] This pull request does not decrease project test coverage
- [x] If the code changes existing database collection(s), migration has been written
- [x] If UI texts are added or changed, all texts are internationalized

## Reviewer checklist
Reviewed by: @username1

This list is to be completed by the pull request reviewer:
- [ ] Code works as described/expected
- [ ] Code seems to be error free
    - [ ] no browser console errors visible
    - [ ] no server console errors visible
    - [ ] passes CI build
- [ ] Code is written in a way that promotes maintainability
    - [ ] easy to understand
    - [ ] well organized
    - [ ] follows project coding standards and conventions
    - [ ] well documented

### CODE REVIEW

**Comment by marla-singer** [comment]
@saransh-dev Another developer is working on the same task about add API via JSON file. Look at his PR, maybe you can find some useful idea
https://github.com/apinf/platform/pull/2973

**Comment by saransh-dev** [comment]
Hi @marla-singer, i need you help i am uploading yaml/Json file from client side by using `DocumentationFiles.insert(event.target.files[0])` but while download this file, it download empty file.

Please advise.

**Comment by marla-singer** [comment]
@saransh-dev I can't help you because the application fails with error on the client side

**Comment by marla-singer** [comment]
Also I don't understand why do you use the modal form? 
Can you add the section like "Add Swagger file" in the Add API page and make the same realisation as "Import API" has? 
joxi_screenshot_1511165071438

**Comment by saransh-dev** [comment]
@marla-singer, I'll push the latest code and let you know

**Comment by saransh-dev** [comment]
@marla-singer I have pushed my updated code.

**Pull request closed without merging**
