### PR TITLE
Update meteor core to 1.4.4.2 & meteor packages

### LINKED ISSUE #2415: Update packages
Meteor has an update, swagger viewer has a (significant) update. Probably a lot of other libraries too. Update time?

### PR DESCRIPTION
**Pull request by brylie**
Closes #2415 

# Changes
- update meteor core to 1.4.4.2
- update package dependencies

```
The following top-level dependencies were not updated to the very latest version available:
 * accounts-base 1.2.17 (1.3.0 is available)  
 * accounts-github 1.2.1 (1.3.0 is available) 
 * aldeed:autoform 5.8.1 (6.1.0 is available) 
 * mizzao:sharejs 0.9.0 (0.10.2 is available) 
 * nimble:restivus 0.8.11 (0.8.12 is available)
                                              
Newer versions of the following indirect dependencies are available:
 * aldeed:collection2-core 1.2.0 (2.0.1 is available)
 * aldeed:schema-deny 1.1.0 (2.0.0 is available)
 * aldeed:schema-index 1.1.1 (2.0.0 is available)
 * ecmascript-runtime 0.3.15 (0.4.0 is available)
```

### CODE REVIEW

**Comment by brylie** [comment]
@apinf/core please review.

**Comment by bajiat** [comment]
@mauriciovieira @marla-singer @frenchbread @55 Can you test this update so that we know that it is safe to update?

**Comment by marla-singer** [comment]
@brylie @bajiat Didn't find any errors. Tested as anonymous user and as admin

**Comment by mauriciovieira** [comment]
@brylie @bajiat @marla-singer LGTM. How many people review meteor updates in our projects before merge, normally?

**Comment by brylie** [comment]
We don't have a strong guideline. Previously, we have had 2-3 developers review, and then @saralavanip has done manual testing on the nightly/staging release branches in general.

**Comment by bajiat** [comment]
@marla-singer Can I assign you as reviewer?

**Comment by frenchbread** [comment]
Works fine for me 👍

**Pull request merged**
