### PR TITLE
Bugfix/for routing

### PR DESCRIPTION
**Pull request by marla-singer**

### CODE REVIEW

**Comment by mauriciovieira** [comment]
@marla-singer it is still showing

> [ERROR] There is no route for the path: /

:-(

**Comment by mauriciovieira** [comment]
@marla-singer thank you for this start. 👍  anyways, i have other problem to run automated test in command line locally, related to tap:i18n. I will follow your idea on to fix the route part.

**Comment by brylie** [comment]
@marla-singer and @mauriciovieira please make sure that every pull request has a proper description and is linked to a related issue. This is part of our working process to encourage transparency with clear communication.

**Comment by mauriciovieira** [comment]
@brylie this was a suggestion to fix a problem on a current pull request, so it was a pull request onto a pull request. I will follow these four bullet points from now on. Thank you.

**Comment by brylie** [comment]
Ah, gotcha. Thanks for clarifying. In that case, it was alright, but a simple description would be helpful.

**Pull request merged**
