### PR TITLE
Harmonize feedback & backlog

### LINKED ISSUE #1826: Harmonize API feedback and API backlog
Select a style for API feedback and API backlog issues and use the same style (e.g. accordeon, panel) on both tabs. Ensure button consistency. 
# Definition of done
- [x] Backlog and Feedback have the same style for items.
- [x] There are no View buttons
- [x] Removing and editing is allowed for
  - [x] all admins
  - [x] The API owner/manager
  - [x] the original writer of feedback item

Open issue: if admin or API owner edits a feedback item created by another user, should there be some notification for 'edited'?

### PR DESCRIPTION
**Pull request by jykae**
Closes #1826 

- also deprecate autoform modals package, not used anymore.

### CODE REVIEW

**Comment by jykae** [comment]
## Preview

Feedback
nayttokuva 2016-11-15 kello 16 17 45

Backlog
nayttokuva 2016-11-15 kello 16 18 08

**Comment by marla-singer** [comment]
@jykae Add underscore in  package.json "depencies" part

**Comment by marla-singer** [comment]
I am anonymous user and try to vote feedback. Had console error
`Error invoking Method 'submitVote': Error: Could not find signed-in user. [apinf-usernotloggedin-error]`
Verified on nightly and I had another error
`Error invoking Method 'submitVote': User id is required [400]`
Found bugs are not related on this task so I will create a issue

**Comment by marla-singer** [comment]
Steps:
1. Create an ordinary user who doesn't manage any api
2. Naavigate to api with feedback
3. Add & save feedback
4. Click on button Edit
 Found: console error with "Access denied"

**Comment by marla-singer** [comment]
How can add the backlog: only owner and apinf administrator or any api managers?

**Comment by jykae** [comment]
@marla-singer Anonymous users are not allowed to vote. I throw error on method, but not catching it on client. It wasn't handled previously, thats why 400 on nightly.

Checking the steps provided..

Yes, backlog can be handled only by API owners/managers & admins

**Comment by jykae** [comment]
@marla-singer fixes ready

**Comment by marla-singer** [comment]
Reviewing

**Comment by marla-singer** [comment]
@jykae Feedback bug was fixed

I have two users: "simple" doesn't have any role and "manager" has role "manager"
joxi_screenshot_1479303101576

But no "simple" and no "manager" can't add backlog to others api
joxi_screenshot_1479303149348
joxi_screenshot_1479303149348 1

Is it as expected? I didn't understand exactly who can add backlog to others api. Or user can add backlog only his own apis?

**Comment by jykae** [comment]
@marla-singer users that have "manager" role have at least one API to manage. However that user must be owner/manager of that particular API to add backlog items.

```
Or user can add backlog only his own apis?
```
So answer to this is Yes.

Otherwise backlog feature would be quite similar to feedback feature.

So I think this is expected behaviour, unless we want to change it in some other task.

**Comment by marla-singer** [comment]
@jykae Okay so I merge it

**Pull request merged**
